importing Required modules

In [183]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import preprocessing as per
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt 
from sklearn_pandas import DataFrameMapper
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.optimizers import SGD
from sklearn.decomposition import PCA
from lifelines.utils import concordance_index
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,median_absolute_error


import deepsurvk
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNetCV
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_squared_error, mean_absolute_error

reading clinical csv file and handling missing values

In [184]:
#READING CSV FILE
df1 = pd.read_csv("data_bcr_clinical_data_patient.csv",na_values='?')
#EXCEPT CLINICAL DATA OTHERS HAVE PATIENT IDs WITH -01, SO ADD -01 AT THE END
df1.at[4,"Patient Identifier"]
def ankfunc(s):
    return s+"-01"
for i in range(4,532):
    df1.at[i,"Patient Identifier"]=ankfunc(df1.at[i,"Patient Identifier"])

#DROP ROWS AND COLUMNS
df1.drop([0,1,2,3] , inplace=True)
df1.set_index("Patient Identifier", inplace=True)

    
df1.replace('unknown',np.nan , inplace=True)
df1.replace('[Not Available]',np.nan , inplace=True)

df1.fillna(df1.mean(), inplace=True)
df1

C:\Users\PRODEE~1\AppData\Local\Temp/ipykernel_20824/2649448865.py:18: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df1.fillna(df1.mean(), inplace=True)

,Patient Primary Tumor Site,Sex,Race Category,Ethnicity Category,Prior Cancer Diagnosis Occurence,Neoadjuvant Therapy Type Administered Prior To Resection Text,Year Cancer Initial Diagnosis,Lymph node neck dissection indicator,Vital Status,American Joint Committee on Cancer Publication Version Type,...,Diagnosis Age,Neoplasm American Joint Committee on Cancer Clinical Distant Metastasis M Stage,Neoplasm American Joint Committee on Cancer Clinical Regional Lymph Node N Stage,Neoplasm American Joint Committee on Cancer Clinical Primary Tumor T Stage,Neoplasm American Joint Committee on Cancer Clinical Group Stage,Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value,Overall Survival Status,Overall Survival (Months),Disease Free Status,Disease Free (Months)
Patient Identifier,,,,,,,,,,,,,,,,,,,,,
TCGA-4P-AA8J-01,Oral Tongue,Male,BLACK OR AFRICAN AMERICAN,NOT HISPANIC OR LATINO,No,No,2013,YES,Alive,7th,...,66,M0,N2a,T4a,Stage IVA,0,0:LIVING,3.35,0:DiseaseFree,3.35
TCGA-BA-4074-01,Oral Tongue,Male,WHITE,NOT HISPANIC OR LATINO,No,No,2003,YES,Dead,6th,...,69,M0,N2c,T3,Stage IVA,0,1:DECEASED,15.18,1:Recurred/Progressed,13.01
TCGA-BA-4075-01,Oral Tongue,Male,BLACK OR AFRICAN AMERICAN,NOT HISPANIC OR LATINO,Yes,Yes,2004,YES,Dead,6th,...,49,M0,N1,T4a,Stage IVA,0,1:DECEASED,9.3,1:Recurred/Progressed,7.75
TCGA-BA-4076-01,Larynx,Male,WHITE,NOT HISPANIC OR LATINO,No,No,2003,YES,Dead,6th,...,39,M0,N2c,T3,Stage IVA,0,1:DECEASED,13.63,1:Recurred/Progressed,9.4
TCGA-BA-4077-01,Base of tongue,Female,WHITE,NOT HISPANIC OR LATINO,Yes,Yes,2003,YES,Dead,6th,...,45,M0,N3,T4b,Stage IVB,0,1:DECEASED,37.25,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-UF-A7JT-01,Floor of mouth,Female,WHITE,NaN,No,No,2009,YES,Dead,6th,...,72,M0,N0,T4a,Stage IVA,0,1:DECEASED,32.62,1:Recurred/Progressed,23.59
TCGA-UF-A7JV-01,Hypopharynx,Female,WHITE,NaN,"Yes, History of Synchronous/Bilateral Malignancy",No,2011,YES,Dead,7th,...,62,M0,N2c,T4a,Stage IVA,0,1:DECEASED,2.96,1:Recurred/Progressed,1.81
TCGA-UP-A6WW-01,Oral Tongue,Male,WHITE,HISPANIC OR LATINO,No,No,2013,YES,Alive,7th,...,58,MX,N2c,T2,Stage IVA,0,0:LIVING,17.02,0:DiseaseFree,17.02
TCGA-WA-A7GZ-01,Floor of mouth,Male,WHITE,NOT HISPANIC OR LATINO,No,No,2012,YES,Dead,7th,...,58,M0,N0,T2,Stage II,0,1:DECEASED,20.53,NaN,NaN
TCGA-WA-A7H4-01,Oral Tongue,Male,WHITE,NOT HISPANIC OR LATINO,No,No,2013,YES,Alive,7th,...,69,M0,N0,T2,Stage II,0,0:LIVING,14.55,0:DiseaseFree,14.55

In [185]:
df1.fillna(method='ffill', inplace=True)
df1.fillna(method='bfill', inplace=True)
df1

,Patient Primary Tumor Site,Sex,Race Category,Ethnicity Category,Prior Cancer Diagnosis Occurence,Neoadjuvant Therapy Type Administered Prior To Resection Text,Year Cancer Initial Diagnosis,Lymph node neck dissection indicator,Vital Status,American Joint Committee on Cancer Publication Version Type,...,Diagnosis Age,Neoplasm American Joint Committee on Cancer Clinical Distant Metastasis M Stage,Neoplasm American Joint Committee on Cancer Clinical Regional Lymph Node N Stage,Neoplasm American Joint Committee on Cancer Clinical Primary Tumor T Stage,Neoplasm American Joint Committee on Cancer Clinical Group Stage,Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value,Overall Survival Status,Overall Survival (Months),Disease Free Status,Disease Free (Months)
Patient Identifier,,,,,,,,,,,,,,,,,,,,,
TCGA-4P-AA8J-01,Oral Tongue,Male,BLACK OR AFRICAN AMERICAN,NOT HISPANIC OR LATINO,No,No,2013,YES,Alive,7th,...,66,M0,N2a,T4a,Stage IVA,0,0:LIVING,3.35,0:DiseaseFree,3.35
TCGA-BA-4074-01,Oral Tongue,Male,WHITE,NOT HISPANIC OR LATINO,No,No,2003,YES,Dead,6th,...,69,M0,N2c,T3,Stage IVA,0,1:DECEASED,15.18,1:Recurred/Progressed,13.01
TCGA-BA-4075-01,Oral Tongue,Male,BLACK OR AFRICAN AMERICAN,NOT HISPANIC OR LATINO,Yes,Yes,2004,YES,Dead,6th,...,49,M0,N1,T4a,Stage IVA,0,1:DECEASED,9.3,1:Recurred/Progressed,7.75
TCGA-BA-4076-01,Larynx,Male,WHITE,NOT HISPANIC OR LATINO,No,No,2003,YES,Dead,6th,...,39,M0,N2c,T3,Stage IVA,0,1:DECEASED,13.63,1:Recurred/Progressed,9.4
TCGA-BA-4077-01,Base of tongue,Female,WHITE,NOT HISPANIC OR LATINO,Yes,Yes,2003,YES,Dead,6th,...,45,M0,N3,T4b,Stage IVB,0,1:DECEASED,37.25,1:Recurred/Progressed,9.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-UF-A7JT-01,Floor of mouth,Female,WHITE,NOT HISPANIC OR LATINO,No,No,2009,YES,Dead,6th,...,72,M0,N0,T4a,Stage IVA,0,1:DECEASED,32.62,1:Recurred/Progressed,23.59
TCGA-UF-A7JV-01,Hypopharynx,Female,WHITE,NOT HISPANIC OR LATINO,"Yes, History of Synchronous/Bilateral Malignancy",No,2011,YES,Dead,7th,...,62,M0,N2c,T4a,Stage IVA,0,1:DECEASED,2.96,1:Recurred/Progressed,1.81
TCGA-UP-A6WW-01,Oral Tongue,Male,WHITE,HISPANIC OR LATINO,No,No,2013,YES,Alive,7th,...,58,MX,N2c,T2,Stage IVA,0,0:LIVING,17.02,0:DiseaseFree,17.02
TCGA-WA-A7GZ-01,Floor of mouth,Male,WHITE,NOT HISPANIC OR LATINO,No,No,2012,YES,Dead,7th,...,58,M0,N0,T2,Stage II,0,1:DECEASED,20.53,0:DiseaseFree,17.02
TCGA-WA-A7H4-01,Oral Tongue,Male,WHITE,NOT HISPANIC OR LATINO,No,No,2013,YES,Alive,7th,...,69,M0,N0,T2,Stage II,0,0:LIVING,14.55,0:DiseaseFree,14.55

encoding the categorical values

In [186]:
df1['Lymph node neck dissection indicator'].replace(['[Not Available]','NO','YES'],['00','1','2'],inplace=True)

df1['Overall Survival Status'].replace(['0:LIVING','1:DECEASED'],['0','1'],inplace=True)
df1['Patient Primary Tumor Site'].replace(['[Not Available]','Buccal Mucosa','Larynx','Oral Cavity','Floor of mouth','Tonsil','Hypopharynx','Alveolar Ridge','Hard Palate','Oropharynx','Lip','Base of tongue','Oral Tongue'],['00','1','2','3','4','5','6','7','8','9','10','11','12'],inplace=True)
df1['Sex'].replace(['[Not Available]','Male','Female'],['00','1','2'],inplace=True)
df1['Race Category'].replace(['[Not Available]','WHITE','BLACK OR AFRICAN AMERICAN','ASIAN','AMERICAN INDIAN OR ALASKA NATIVE'],['00','1','2','3','4'],inplace=True)
df1['Ethnicity Category'].replace(['[Not Available]','NOT HISPANIC OR LATINO','HISPANIC OR LATINO'],['00','1','2'],inplace=True)
df1['Prior Cancer Diagnosis Occurence'].replace(['[Not Available]','No','Yes','Yes, History of Synchronous/Bilateral Malignancy','Yes, History of Prior Malignancy'],['00','1','2','3','4'],inplace=True)
df1['Neoadjuvant Therapy Type Administered Prior To Resection Text'].replace(['[Not Available]','No','Yes'],['00','1','2'],inplace=True)
df1['Vital Status'].replace(['[Not Available]','Dead','Alive'],['00','1','2'],inplace=True)
df1['American Joint Committee on Cancer Publication Version Type'].replace(['[Not Available]','6th','7th','5th','4th'],['00','1','2','3','4'],inplace=True)
df1['American Joint Committee on Cancer Tumor Stage Code'].replace(['[Not Available]','T0','T1','T2','T3','T4','T4a','T4b','TX'],['00','1','2','3','4','5','6','7','8'],inplace=True)
df1['Disease Free Status'].replace(['0:DiseaseFree','1:Recurred/Progressed','[Not Available]'],['0','1','00'],inplace=True)
df1['Neoplasm Histologic Grade'].replace(['[Not Available]','G1','G2','G3','GX','G4'],['00','1','2','3','4','5'],inplace=True)
df1['Alcohol History Documented'].replace(['[Not Available]','No','Yes','NO','YES'],['00','1','2','3','4'],inplace=True)
df1['Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code'].replace(['[Not Available]','N0','N1','N2','N2a','N2b','N2c','N3','NX'],['00','1','2','3','4','5','6','7','8'],inplace=True)
df1['Neoplasm Disease Stage American Joint Committee on Cancer Code'].replace(['[Not Available]','Discrepancy','Stage I','Stage II','Stage III','Stage IVA','Stage IVB','Stage IVC'],['00','00','1','2','3','4','5','6'],inplace=True)
df1['Neoplasm American Joint Committee on Cancer Clinical Distant Metastasis M Stage'].replace(['[Not Available]','M1','M1','MX','M0'],['00','1','2','3','4'],inplace=True)
df1['Neoplasm American Joint Committee on Cancer Clinical Regional Lymph Node N Stage'].replace(['[Not Available]','N0','N1','N2a','N2b','N2c','N3','NX','N2'],['00','1','2','3','4','5','6','7','8'],inplace=True)
df1['Neoplasm American Joint Committee on Cancer Clinical Primary Tumor T Stage'].replace(['[Not Available]','T1','T2','T3','T4a','T4b','TX','T4'],['00','1','2','3','4','5','6','7'],inplace=True)
df1['Neoplasm American Joint Committee on Cancer Clinical Group Stage'].replace(['[Not Available]','Stage I','Stage II','Stage III','Stage IVA','Stage IVB','Stage IVC'],['00','1','2','3','4','5','6'],inplace=True)

df1.head()

,Patient Primary Tumor Site,Sex,Race Category,Ethnicity Category,Prior Cancer Diagnosis Occurence,Neoadjuvant Therapy Type Administered Prior To Resection Text,Year Cancer Initial Diagnosis,Lymph node neck dissection indicator,Vital Status,American Joint Committee on Cancer Publication Version Type,...,Diagnosis Age,Neoplasm American Joint Committee on Cancer Clinical Distant Metastasis M Stage,Neoplasm American Joint Committee on Cancer Clinical Regional Lymph Node N Stage,Neoplasm American Joint Committee on Cancer Clinical Primary Tumor T Stage,Neoplasm American Joint Committee on Cancer Clinical Group Stage,Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value,Overall Survival Status,Overall Survival (Months),Disease Free Status,Disease Free (Months)
Patient Identifier,,,,,,,,,,,,,,,,,,,,,
TCGA-4P-AA8J-01,12,1,2,1,1,1,2013,2,2,2,...,66,4,3,4,4,0,0,3.35,0,3.35
TCGA-BA-4074-01,12,1,1,1,1,1,2003,2,1,1,...,69,4,5,3,4,0,1,15.18,1,13.01
TCGA-BA-4075-01,12,1,2,1,2,2,2004,2,1,1,...,49,4,2,4,4,0,1,9.3,1,7.75
TCGA-BA-4076-01,2,1,1,1,1,1,2003,2,1,1,...,39,4,5,3,4,0,1,13.63,1,9.4
TCGA-BA-4077-01,11,2,1,1,2,2,2003,2,1,1,...,45,4,6,5,5,0,1,37.25,1,9.4

In [187]:
#STORING REDUCED DATA TO CSV
cl = pd.DataFrame(df1)
cl.to_csv("CLINICALpreprocessed.csv")
print("Data exported to csv file")

Data exported to csv file

Reading methylation data and handling missing values

In [188]:
#READING CSV FILE
df =pd.read_csv("data_methylation_hm450.csv")

#DROP ROWS AND COLUMNS
df =df.dropna()
df.drop("Entrez_Gene_Id", axis=1 ,inplace=True)

#SET INDEX
df.set_index('Hugo_Symbol', inplace=True)

#TRANSPOSE ROWS INTO COLUMNS
df2 = df.T
df2.to_csv("Methylation.csv")
df2.head()

Hugo_Symbol,TSEN34,MUSTN1,C3orf16,CKLF,SFRS7,FAM180B,PTPRF,C6orf168,LOC728024,DSTYK,...,VDAC1,DDX46,FAM13B,IL12B,PHACTR2,PRKRIP1,AGK,EZH2,AUH,ZNF189
TCGA-4P-AA8J-01,0.160658,0.856690,0.689981,0.063268,0.088333,0.738956,0.689032,0.485472,0.847822,0.018144,...,0.021239,0.095778,0.061835,0.043785,0.055341,0.066497,0.080675,0.041548,0.054317,0.098915
TCGA-BA-4074-01,0.172720,0.888797,0.448310,0.095680,0.054274,0.506644,0.842746,0.188788,0.916802,0.018413,...,0.036593,0.086075,0.057365,0.059737,0.047445,0.075115,0.154639,0.076333,0.070420,0.097873
TCGA-BA-4075-01,0.091838,0.876359,0.336352,0.079018,0.062922,0.475571,0.783786,0.221566,0.792347,0.021204,...,0.034351,0.100891,0.048480,0.053835,0.059135,0.095026,0.116404,0.073396,0.082182,0.077774
TCGA-BA-4076-01,0.127324,0.911893,0.757925,0.095460,0.073372,0.834641,0.718938,0.791580,0.898727,0.014496,...,0.024872,0.075242,0.044595,0.050950,0.026872,0.111361,0.222005,0.057531,0.038989,0.064009
TCGA-BA-4077-01,0.132946,0.893790,0.556940,0.074819,0.080927,0.773512,0.392731,0.283078,0.857577,0.018026,...,0.034238,0.067696,0.043182,0.051532,0.054207,0.148919,0.097344,0.052320,0.045407,0.069227

merging the clincal and methylation dataset for extracting survival time which is required for feature selection

In [189]:
# Merge datasets based on the patient identifier
merged_df = pd.merge(cl, df2, left_index=True, right_index=True, how="inner")
df2=merged_df

In [190]:

c2 = pd.DataFrame(df2)
c2.to_csv("Methylationpreprocessed.csv")

In [191]:

# Extract target variable (survival time) from clinical data
y = c2['Overall Survival (Months)']
c2 = c2.drop('Overall Survival (Months)', axis=1)

In [192]:
y.drop(y.index[-1], inplace=True)
dm=c2.iloc[:,:]
#print(d)
dm = dm.reset_index()
M=dm.iloc[1:,1:]
M

,Patient Primary Tumor Site,Sex,Race Category,Ethnicity Category,Prior Cancer Diagnosis Occurence,Neoadjuvant Therapy Type Administered Prior To Resection Text,Year Cancer Initial Diagnosis,Lymph node neck dissection indicator,Vital Status,American Joint Committee on Cancer Publication Version Type,...,VDAC1,DDX46,FAM13B,IL12B,PHACTR2,PRKRIP1,AGK,EZH2,AUH,ZNF189
1,12,1,1,1,1,1,2003,2,1,1,...,0.036593,0.086075,0.057365,0.059737,0.047445,0.075115,0.154639,0.076333,0.070420,0.097873
2,12,1,2,1,2,2,2004,2,1,1,...,0.034351,0.100891,0.048480,0.053835,0.059135,0.095026,0.116404,0.073396,0.082182,0.077774
3,2,1,1,1,1,1,2003,2,1,1,...,0.024872,0.075242,0.044595,0.050950,0.026872,0.111361,0.222005,0.057531,0.038989,0.064009
4,11,2,1,1,2,2,2003,2,1,1,...,0.034238,0.067696,0.043182,0.051532,0.054207,0.148919,0.097344,0.052320,0.045407,0.069227
5,2,1,1,1,1,1,2003,2,1,1,...,0.036186,0.065871,0.042553,0.043962,0.036412,0.131708,0.062926,0.043616,0.044998,0.057528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,4,2,1,1,1,1,2009,2,1,1,...,0.019317,0.045418,0.032703,0.032664,0.035815,0.044621,0.080887,0.037113,0.033082,0.048041
524,6,2,1,1,3,1,2011,2,1,2,...,0.030936,0.068638,0.042534,0.043967,0.047700,0.063594,0.094378,0.045045,0.049718,0.084455
525,12,1,1,2,1,1,2013,2,2,2,...,0.024656,0.044608,0.030440,0.047566,0.064576,0.062233,0.051034,0.034986,0.053662,0.051514
526,4,1,1,1,1,1,2012,2,1,2,...,0.026150,0.078658,0.047960,0.048287,0.050811,0.059785,0.077223,0.051496,0.048270,0.059510
527,12,1,1,1,1,1,2013,2,2,2,...,0.022645,0.049174,0.034855,0.040104,0.042831,0.083575,0.068414,0.042270,0.041004,0.059354

Applying PCA Dimensionality reduction to reduce features. Dimensionality reduction is the process of reducing the number of features (or dimensions) in a dataset while retaining as much information as possible. This can be done for a variety of reasons, such as to reduce the complexity of a model, to improve the performance of a learning algorithm, or to make it easier to visualize the data. There are several techniques for dimensionality reduction, including principal component analysis (PCA), singular value decomposition (SVD), and linear discriminant analysis (LDA).

In [193]:
#standardize the data
scaler = StandardScaler()
X1 = scaler.fit_transform(M[:])
#PCA 
# fit pca on data
pca = PCA(.95)
pca.fit(X1)
Z1=pca.transform(X1)

Applying RFE Feature Selection methods. Feature selection is a crucial step in the process of building machine learning models. It involves selecting a subset of relevant features from the original set of features to improve model performance, reduce overfitting, and enhance interpretability. some important feature selection methods are RFE, LASSO, Random Forest etc.

In [194]:
n1 = pd.DataFrame(Z1)
print(n1.shape)
hugo=[]
for i in range(1,528):
    hugo.append(dm['index'][i])
n1["Hugo"]=hugo
n1

(527, 387)

,0,1,2,3,4,5,6,7,8,9,...,378,379,380,381,382,383,384,385,386,Hugo
0,37.966740,27.460375,-1.044253,-32.311313,-17.216051,-35.772245,15.875630,-5.593684,-7.900892,-8.992877,...,-1.197591,-0.017473,0.833896,-0.593338,0.530102,0.400313,0.405037,2.036243,2.350268,TCGA-BA-4074-01
1,-11.652303,86.681811,47.471653,-7.123739,28.939181,-15.349657,-11.138881,-10.460588,6.572495,-2.113885,...,-0.061747,-0.192846,-0.176073,0.370619,-0.201172,-0.091598,0.252628,0.108090,-0.059275,TCGA-BA-4075-01
2,-52.592312,-15.064044,61.067690,-4.594665,25.017990,-14.316248,-21.350068,11.244861,0.231650,2.776049,...,1.089667,0.993366,-0.993392,-0.315855,0.089883,0.403941,-1.526601,0.190003,0.195282,TCGA-BA-4076-01
3,5.490346,-8.517104,28.211523,26.724543,4.364628,-3.053363,-14.871908,-32.010688,3.442884,13.074267,...,-0.028704,4.103890,4.781313,-0.207200,3.480504,4.090014,1.096236,0.859647,2.136359,TCGA-BA-4077-01
4,24.812767,-30.783921,45.110594,57.120804,-13.997583,-22.305011,-13.343090,13.943742,3.410954,5.255301,...,1.780084,0.549635,0.033169,0.705854,0.460278,0.187197,-0.701312,0.114315,-0.432564,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,-19.000191,-0.087101,-7.152378,-28.030376,12.615967,52.431953,0.527690,20.290588,8.299339,-3.487190,...,-4.332372,-9.966922,-1.580057,-1.750617,3.357426,1.785039,3.091627,1.148432,2.618686,TCGA-UF-A7JT-01
523,-26.270457,19.437747,-19.179308,-21.005025,16.054569,12.828012,9.676075,5.432176,-20.396517,-11.095898,...,1.318324,0.753022,0.972786,-0.295753,-1.957052,1.815467,0.758309,0.073926,2.116196,TCGA-UF-A7JV-01
524,23.757266,-9.124223,39.910962,52.611628,-20.907197,63.207499,6.797034,-17.175075,-22.865997,-15.471139,...,1.449544,-0.337607,-1.963079,-0.394910,-0.242033,1.158878,1.268838,-0.567229,-0.807137,TCGA-UP-A6WW-01
525,77.957372,29.350011,-36.095846,22.874074,102.381682,87.737924,-33.493274,0.916156,48.986830,-28.932604,...,-0.836093,-0.532140,0.307996,-0.128586,0.250432,-0.168276,0.256733,-0.151562,-0.159189,TCGA-WA-A7GZ-01
526,17.287541,-3.405047,-48.334938,5.772322,25.660522,9.681102,-5.233825,-4.649571,-10.893919,-11.410735,...,2.323909,1.089752,-0.856056,4.695505,2.391395,1.677479,1.831549,-1.008018,-0.106783,TCGA-WA-A7H4-01

In [195]:

lasso = Lasso(alpha=0.1)  # alpha is the regularization strength
lasso.fit(Z1, y)
n_components = Z1.shape[1]
feature_names = [i+1 for i in range(n_components)]
coef = pd.Series(lasso.coef_, index=feature_names)
selected_features = coef.abs().nlargest(346).index
print("Number of selected features: ", len(selected_features))
print("Selected features: ", selected_features)
try:
    columns = []
    for i in selected_features:
        column = Z1[:, i]
        columns.append(column)
except Exception:
    pass
Zl1 = np.column_stack(columns)
nl1 = pd.DataFrame(Zl1)
print(nl1.shape)
hugo=[]
for i in range(1,528):
    hugo.append(dm['index'][i])
nl1["Hugo"]=hugo
nl1

Number of selected features:  346
Selected features:  Int64Index([326, 383, 241, 236, 235, 387, 159, 249, 331, 344,
            ...
            385, 219, 254, 329, 252,  99, 244,  71, 245, 147],
           dtype='int64', length=346)
(527, 5)

            0         1         2         3         4             Hugo
0   -3.658568  0.400313  3.492564  3.273421  6.950992  TCGA-BA-4074-01
1    0.090342 -0.091598  0.204159 -0.468069  0.656066  TCGA-BA-4075-01
2   -1.414555  0.403941  1.720904  0.023478  1.557886  TCGA-BA-4076-01
3    3.201512  4.090014 -0.464714 -4.734936  3.149420  TCGA-BA-4077-01
4   -1.801714  0.187197 -0.463345  1.361140 -0.990065  TCGA-BA-4078-01
..        ...       ...       ...       ...       ...              ...
522 -3.509492  1.785039 -2.285356 -2.921171 -3.295175  TCGA-UF-A7JT-01
523  2.602773  1.815467 -6.034947  5.229396  7.959944  TCGA-UF-A7JV-01
524 -1.842153  1.158878 -1.480972  2.596367 -2.669407  TCGA-UP-A6WW-01
525  0.265990 -0.168276 -0.983755 -1.021214  1.638513  TCGA-WA-A7GZ-01
526 -2.771570  1.677479  2.598050 -3.537942 -0.419804  TCGA-WA-A7H4-01

[527 rows x 6 columns]

In [196]:
en = ElasticNetCV(l1_ratio=0.5, cv=5)
en.fit(Z1, y)
coef = pd.Series(en.coef_, index=[i+1 for i in range(Z1.shape[1])])
selected_features = coef.abs().nlargest(346).index
print("Number of selected features: ", len(selected_features))
print("Selected features: ", selected_features.tolist())
try:
    columns = []
    for i in selected_features:
        column = Z1[:, i]
        columns.append(column)
except Exception:
    pass
Ze1 = np.column_stack(columns)
ne1 = pd.DataFrame(Ze1)
ne1.shape
hugo=[]
for i in range(1,528):
    hugo.append(dm['index'][i])
ne1["Hugo"]=hugo
ne1

G:\ana\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 190.62089106472558, tolerance: 37.95947935254157
  model = cd_fast.enet_coordinate_descent_gram(
G:\ana\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 386.813833243752, tolerance: 37.95947935254157
  model = cd_fast.enet_coordinate_descent_gram(
G:\ana\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 593.0581629316075, tolerance: 37.95947935254157
  model = cd_fast.enet_coordinate_descent_gram(
G:\ana\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 755.6140003167529, tolerance: 37.95947935254157
  model = cd_fast.enet_coordinate_descent_gram(
G:\ana\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1068.7737440664641, tolerance: 37.95947935254157
  model = cd_fast.enet_coordinate_descent_gram(
G:\ana\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1332.6308740153254, tolerance: 37.95947935254157
  model = cd_fast.enet_coordinate_descent_gram(
G:\ana\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1022.0763348706605, tolerance: 37.95947935254157
  model = cd_fast.enet_coordinate_descent_gram(
G:\ana\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1501.8574127453612, tolerance: 37.95947935254157
  model = cd_fast.enet_coordinate_descent_gram(
G:\ana\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1428.6173635135128, tolerance: 37.95947935254157
  model = cd_fast.enet_coordinate_descent_gram(
G:\ana\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1446.7050606912308, tolerance: 37.95947935254157
  model = cd_fast.enet_coordinate_descent_gram(
G:\ana\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1792.6262721181774, tolerance: 37.95947935254157
  model = cd_fast.enet_coordinate_descent_gram(

Number of selected features:  346
Selected features:  [7, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346]

,0,1,2,3,4,5,6,7,8,9,...,337,338,339,340,341,342,343,344,345,Hugo
0,-5.593684,27.460375,-1.044253,-32.311313,-17.216051,-35.772245,15.875630,-7.900892,-8.992877,16.529898,...,-0.465413,1.551939,1.187870,0.701429,-1.758934,1.210298,0.232179,-1.372118,3.120576,TCGA-BA-4074-01
1,-10.460588,86.681811,47.471653,-7.123739,28.939181,-15.349657,-11.138881,6.572495,-2.113885,1.708659,...,0.023468,-0.114919,-0.016531,-0.148982,-0.118711,-0.003628,-0.034947,-0.135351,-0.388050,TCGA-BA-4075-01
2,11.244861,-15.064044,61.067690,-4.594665,25.017990,-14.316248,-21.350068,0.231650,2.776049,0.931249,...,-0.277611,-0.670777,0.308999,-0.292876,-0.806699,-1.758266,-0.705704,0.174518,-1.657010,TCGA-BA-4076-01
3,-32.010688,-8.517104,28.211523,26.724543,4.364628,-3.053363,-14.871908,3.442884,13.074267,-8.700608,...,1.997848,0.000567,-1.105868,0.998472,0.460741,-3.662214,-5.094245,-1.302245,-1.793985,TCGA-BA-4077-01
4,13.943742,-30.783921,45.110594,57.120804,-13.997583,-22.305011,-13.343090,3.410954,5.255301,7.977272,...,1.274889,-1.254015,0.654373,0.463495,0.552568,0.477954,-1.163829,1.934047,1.939721,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,20.290588,-0.087101,-7.152378,-28.030376,12.615967,52.431953,0.527690,8.299339,-3.487190,-12.992510,...,-4.666328,1.412587,3.413485,-5.350936,-1.945754,-9.568405,-3.569576,0.071057,-6.598378,TCGA-UF-A7JT-01
523,5.432176,19.437747,-19.179308,-21.005025,16.054569,12.828012,9.676075,-20.396517,-11.095898,2.527732,...,2.346084,-0.725488,-0.598607,1.302829,-4.596201,-3.355274,-1.686343,1.742633,-0.765317,TCGA-UF-A7JV-01
524,-17.175075,-9.124223,39.910962,52.611628,-20.907197,63.207499,6.797034,-22.865997,-15.471139,34.165472,...,0.624906,0.110281,-0.975688,-2.003180,-0.716300,-0.319209,0.283684,0.092445,0.415906,TCGA-UP-A6WW-01
525,0.916156,29.350011,-36.095846,22.874074,102.381682,87.737924,-33.493274,48.986830,-28.932604,62.057055,...,0.163244,0.237657,0.253281,-0.537293,0.617904,-0.293070,-0.528130,-0.073537,0.116448,TCGA-WA-A7GZ-01
526,-4.649571,-3.405047,-48.334938,5.772322,25.660522,9.681102,-5.233825,-10.893919,-11.410735,17.167533,...,-3.403760,-1.815836,0.877215,0.516923,-0.258222,0.279567,-1.159056,0.525274,-0.532534,TCGA-WA-A7H4-01

In [197]:
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(Z1, y)
importances = rf.feature_importances_
feature_names = [i+1 for i in range(Z1.shape[1])]
importance_df = pd.DataFrame({"Feature": feature_names, "Importance": importances})
importance_df.sort_values("Importance", ascending=False, inplace=True)
selected_features = importance_df["Feature"].head(346)
print("Number of selected features: ", len(selected_features))
print("Selected features: ", selected_features.tolist())
try:
    columns = []
    for i in selected_features:
        column = Z1[:, i]
        columns.append(column)
except Exception:
    pass
Zrf1 = np.column_stack(columns)
nrf1 = pd.DataFrame(Zrf1)
nrf1.shape
hugo=[]
for i in range(1,528):
    hugo.append(dm['index'][i])
nrf1["Hugo"]=hugo
nrf1

Number of selected features:  346
Selected features:  [161, 281, 171, 273, 217, 216, 112, 7, 11, 310, 21, 169, 83, 178, 336, 130, 37, 236, 211, 337, 187, 38, 34, 339, 3, 202, 195, 375, 133, 16, 347, 36, 22, 380, 151, 191, 344, 13, 277, 356, 383, 352, 387, 368, 268, 248, 235, 343, 322, 363, 382, 158, 379, 8, 165, 159, 168, 96, 384, 91, 287, 31, 306, 325, 123, 32, 333, 184, 115, 10, 33, 300, 345, 290, 230, 135, 257, 226, 131, 267, 28, 19, 296, 18, 357, 323, 360, 73, 2, 146, 225, 42, 136, 265, 213, 206, 167, 256, 205, 196, 80, 118, 15, 128, 75, 153, 266, 210, 43, 293, 35, 355, 124, 282, 238, 232, 295, 386, 374, 366, 367, 1, 335, 227, 259, 373, 92, 54, 199, 376, 6, 154, 162, 110, 144, 370, 301, 114, 279, 172, 294, 190, 330, 174, 297, 55, 126, 340, 157, 138, 63, 341, 14, 125, 280, 192, 304, 331, 69, 68, 328, 283, 292, 250, 316, 189, 218, 309, 111, 263, 308, 208, 359, 298, 152, 351, 129, 258, 12, 193, 203, 117, 365, 254, 62, 243, 30, 176, 378, 182, 338, 326, 66, 132, 278, 289, 141, 261, 119, 249, 334, 201, 56, 103, 166, 219, 5, 212, 200, 353, 262, 221, 188, 372, 93, 150, 253, 163, 185, 140, 106, 332, 155, 51, 53, 17, 113, 177, 104, 98, 302, 67, 94, 312, 349, 222, 241, 40, 269, 361, 149, 89, 233, 108, 285, 286, 377, 107, 9, 41, 313, 264, 142, 44, 39, 147, 77, 25, 321, 270, 179, 215, 145, 79, 358, 105, 244, 57, 317, 291, 314, 242, 50, 47, 183, 198, 329, 164, 381, 239, 228, 255, 342, 252, 350, 354, 160, 224, 327, 29, 207, 87, 272, 274, 95, 346, 237, 122, 20, 170, 116, 90, 288, 246, 197, 247, 85, 84, 143, 52, 245, 214, 240, 76, 324, 220, 88, 120, 148, 137, 156, 74, 65, 307, 315, 173, 204, 229, 139, 319, 251, 45, 127, 385, 60, 284, 318, 181, 320, 61, 275, 299, 134, 48, 194, 371]

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,Hugo
0,-2.612274,-1.769997,1.854371,-3.773283,11.290332,12.556277,-5.297164,-5.593684,8.126443,0.202289,...,0.833896,3.177549,-5.011269,0.232179,-2.127261,4.045776,-0.242007,0.400313,-1.391639,TCGA-BA-4074-01
1,0.474752,0.145462,0.858455,0.431406,-0.727539,-0.626044,2.534165,-10.460588,-2.036876,-0.273958,...,-0.176073,0.285851,0.111265,-0.034947,-7.474749,-0.030796,0.102525,-0.091598,-0.016037,TCGA-BA-4075-01
2,-2.600840,1.690488,-1.589571,-2.959973,0.916006,2.713202,-1.405123,11.244861,-3.040855,0.463552,...,-0.993392,-0.897008,-0.193880,-0.705704,-34.465105,0.849600,-0.702190,0.403941,-0.530241,TCGA-BA-4076-01
3,-0.821585,-0.514935,-2.174618,-2.904709,-1.160107,-4.151443,2.385432,-32.010688,-2.625206,-4.202990,...,4.781313,-4.630303,-5.883377,-5.094245,-6.954599,3.545657,-0.060601,4.090014,-6.465943,TCGA-BA-4077-01
4,7.641019,-0.851562,3.620662,1.703112,1.390379,-6.884233,-6.408731,13.943742,0.243871,0.136010,...,0.033169,-2.326549,-4.562521,-1.163829,15.237576,1.580729,-0.528227,0.187197,-0.905325,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,0.171570,-0.812919,-2.024853,3.161666,1.617779,0.584843,1.681061,20.290588,2.995235,-10.856072,...,-1.580057,0.494685,-3.247802,-3.569576,4.333409,-3.256535,3.663996,1.785039,-3.753992,TCGA-UF-A7JT-01
523,3.840060,4.089960,-2.805565,0.970071,-9.688899,1.490580,-7.552429,5.432176,12.014618,0.751587,...,0.972786,3.692412,-0.787486,-1.686343,-4.306876,4.626864,1.094084,1.815467,-3.575434,TCGA-UF-A7JV-01
524,-1.582976,-1.189204,3.870143,1.605812,-1.394888,-2.470205,-19.690538,-17.175075,-4.376453,-0.539537,...,-1.963079,-0.857153,-5.916692,0.283684,12.415976,-1.744848,2.316346,1.158878,1.094549,TCGA-UP-A6WW-01
525,-0.019521,-0.661618,0.551586,-0.530225,-0.421237,-1.805437,-0.964183,0.916156,-21.179768,1.276544,...,0.307996,-2.350883,-0.490885,-0.528130,-44.169307,0.417257,-0.165667,-0.168276,-0.160212,TCGA-WA-A7GZ-01
526,-0.700809,0.635156,0.140343,-0.516206,0.385454,-1.564654,0.120729,-4.649571,4.565298,-0.845950,...,-0.856056,-1.177214,0.724853,-1.159056,9.968842,0.799408,-0.778685,1.677479,-0.778452,TCGA-WA-A7H4-01

In [198]:
lr = LinearRegression()
rfe = RFE(lr, n_features_to_select=346)
rfe.fit(Z1, y)
selected_features = [i+1 for i in range(len(rfe.support_)) if rfe.support_[i]]
print("Selected Features:", selected_features)
try:
    columns = []
    for i in selected_features:
        column = Z1[:, i]
        columns.append(column)
except Exception:
    pass
Zre1 = np.column_stack(columns)
nre1 = pd.DataFrame(Zre1)
nre1.shape
hugo=[]
for i in range(1,528):
    hugo.append(dm['index'][i])
nre1["Hugo"]=hugo
nre1

Selected Features: [5, 6, 7, 10, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 47, 48, 49, 50, 51, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 67, 68, 69, 70, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 94, 96, 98, 100, 101, 102, 103, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 165, 166, 168, 169, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 280, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 306, 307, 308, 309, 310, 311, 312, 314, 316, 317, 319, 320, 321, 322, 323, 324, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 351, 352, 353, 354, 356, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387]

,0,1,2,3,4,5,6,7,8,9,...,336,337,338,339,340,341,342,343,344,Hugo
0,-35.772245,15.875630,-5.593684,16.529898,-5.903702,-2.127261,-0.377044,2.060890,-3.072572,7.159269,...,-1.197591,-0.017473,0.833896,-0.593338,0.530102,0.400313,0.405037,2.036243,2.350268,TCGA-BA-4074-01
1,-15.349657,-11.138881,-10.460588,1.708659,-24.139966,-7.474749,-43.920955,-7.678469,-40.083581,43.041716,...,-0.061747,-0.192846,-0.176073,0.370619,-0.201172,-0.091598,0.252628,0.108090,-0.059275,TCGA-BA-4075-01
2,-14.316248,-21.350068,11.244861,0.931249,20.151574,-34.465105,9.910241,41.344078,-5.257676,-5.649413,...,1.089667,0.993366,-0.993392,-0.315855,0.089883,0.403941,-1.526601,0.190003,0.195282,TCGA-BA-4076-01
3,-3.053363,-14.871908,-32.010688,-8.700608,5.388567,-6.954599,-10.499644,22.467996,-12.405529,6.682472,...,-0.028704,4.103890,4.781313,-0.207200,3.480504,4.090014,1.096236,0.859647,2.136359,TCGA-BA-4077-01
4,-22.305011,-13.343090,13.943742,7.977272,-17.489836,15.237576,-6.241609,-6.530951,-18.147118,3.272823,...,1.780084,0.549635,0.033169,0.705854,0.460278,0.187197,-0.701312,0.114315,-0.432564,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,52.431953,0.527690,20.290588,-12.992510,4.323593,4.333409,-9.763697,-1.249041,-14.949194,-2.416085,...,-4.332372,-9.966922,-1.580057,-1.750617,3.357426,1.785039,3.091627,1.148432,2.618686,TCGA-UF-A7JT-01
523,12.828012,9.676075,5.432176,2.527732,8.894714,-4.306876,-27.764684,-9.741121,-1.571661,12.478862,...,1.318324,0.753022,0.972786,-0.295753,-1.957052,1.815467,0.758309,0.073926,2.116196,TCGA-UF-A7JV-01
524,63.207499,6.797034,-17.175075,34.165472,13.107518,12.415976,-14.272440,-8.248232,-5.568044,5.124038,...,1.449544,-0.337607,-1.963079,-0.394910,-0.242033,1.158878,1.268838,-0.567229,-0.807137,TCGA-UP-A6WW-01
525,87.737924,-33.493274,0.916156,62.057055,7.912945,-44.169307,12.078353,-57.427969,-0.899998,12.325944,...,-0.836093,-0.532140,0.307996,-0.128586,0.250432,-0.168276,0.256733,-0.151562,-0.159189,TCGA-WA-A7GZ-01
526,9.681102,-5.233825,-4.649571,17.167533,6.637154,9.968842,0.840255,0.218688,3.831471,0.460524,...,2.323909,1.089752,-0.856056,4.695505,2.391395,1.677479,1.831549,-1.008018,-0.106783,TCGA-WA-A7H4-01

Reading mRNA data and handling missing values

In [199]:
#READING CSV FILE
df = pd.read_csv("data_RNA_Seq_v2_expression_median.csv")

#DROP ROWS AND COLUMNS
df=df.replace(0,np.nan)
df=df.dropna()
df=df.replace(np.nan,0)
df.drop("Entrez_Gene_Id", axis=1 ,inplace=True)

#SET INDEX
df.set_index('Hugo_Symbol', inplace=True)

#TRANSPOSE ROWS INTO COLUMNS
df4 = df.T
df4.to_csv("RNAb.csv")
df4.head()
merged_df = pd.merge(cl, df4, left_index=True, right_index=True, how="inner")
df4=merged_df

In [200]:
c4 = pd.DataFrame(df4)
c4.to_csv("RNApreprocessed.csv")
y = c4['Overall Survival (Months)']
c4 = c4.drop('Overall Survival (Months)', axis=1)
y.drop(y.index[-1], inplace=True)
drn=c4.iloc[:,:]
#print(d)
drn = drn.reset_index()
Rn=drn.iloc[1:,1:]
Rn.head()

,Patient Primary Tumor Site,Sex,Race Category,Ethnicity Category,Prior Cancer Diagnosis Occurence,Neoadjuvant Therapy Type Administered Prior To Resection Text,Year Cancer Initial Diagnosis,Lymph node neck dissection indicator,Vital Status,American Joint Committee on Cancer Publication Version Type,...,LOC154274,ZW10,ZWILCH,ZWINT,ZXDB,LOC100130182,ZYG11B,ZYX,FLJ10821,ZZZ3
1,12,1,1,1,1,1,2003,2,1,1,...,311.0030,283.6409,2132.4595,1193.1417,172.2656,380.3717,805.0624,2516.9279,258.5911,1088.3179
2,12,1,2,1,2,2,2004,2,1,1,...,225.1105,512.3945,761.0023,673.1877,172.0488,562.2404,487.7395,5930.0549,292.6437,980.3028
3,2,1,1,1,1,1,2003,2,1,1,...,157.9431,307.4905,480.0682,1032.6643,324.2818,1440.9025,722.5502,2674.5376,672.1763,998.5570
4,11,2,1,1,2,2,2003,2,1,1,...,137.6323,361.4052,1325.3128,1620.3080,210.7796,1423.0029,770.9336,8035.6112,763.2339,692.9740
5,2,1,1,1,1,1,2003,2,1,1,...,241.8520,414.1231,874.1257,1145.1112,372.9953,2634.2473,780.1345,3895.2406,1556.6477,1309.6223

Applying PCA dimensioality reduction technique

In [201]:
#PCA 
scaler = StandardScaler()
# Fit on training set only.
X3 = scaler.fit_transform(Rn[:])
#fit pca on data
pca = PCA(.95)
pca.fit(X3)
#transform pca
Z3 =pca.transform(X3)
Z3

array([[ 6.01180987e+01,  2.61402513e+01, -6.41804813e+01, ...,
         1.11854553e+00,  2.13596624e-01, -6.96500953e-01],
       [ 4.36270030e+01, -1.23970413e+01, -3.78874657e+01, ...,
        -7.77263360e-01, -1.80791006e-01,  1.69481651e-01],
       [ 1.01490858e+00, -1.64933334e+01, -2.51350641e+01, ...,
         1.03313340e+00, -1.13632574e+00,  3.13676315e-01],
       ...,
       [ 7.84703830e+01,  5.59797890e+01,  1.06242418e+01, ...,
         1.50499021e+00, -6.49656472e-02, -7.68826430e-01],
       [ 6.35037415e+00,  5.82697398e+00, -1.28607259e+01, ...,
        -1.57927902e+00,  9.00642061e-02, -1.66646656e-01],
       [-1.18995009e+01,  1.43759827e+01,  1.51147650e+01, ...,
         2.99135926e+00,  2.69296881e+00, -1.22700645e+00]])

Applying RFE Feature selection methods

In [202]:
n3 = pd.DataFrame(Z3)
hugo=[]
for i in range(1,520):
    hugo.append(drn['index'][i])
n3["Hugo"]=hugo
n3

,0,1,2,3,4,5,6,7,8,9,...,314,315,316,317,318,319,320,321,322,Hugo
0,60.118099,26.140251,-64.180481,84.128182,135.132266,118.150329,53.186133,59.027978,-17.676262,-3.691583,...,0.382470,-0.217832,-0.057020,0.325537,0.694952,-0.482477,1.118546,0.213597,-0.696501,TCGA-BA-4074-01
1,43.627003,-12.397041,-37.887466,67.227723,89.696953,67.235101,24.330854,26.330579,-15.242053,-4.606208,...,-1.212201,-1.345564,0.412864,0.740884,0.137020,0.459506,-0.777263,-0.180791,0.169482,TCGA-BA-4075-01
2,1.014909,-16.493333,-25.135064,17.473437,11.606667,25.737596,-9.259798,15.763583,-13.589997,-14.311950,...,1.342636,0.410531,-0.137815,-2.072257,0.659747,0.066044,1.033133,-1.136326,0.313676,TCGA-BA-4076-01
3,-5.197779,1.672591,3.526023,-12.276289,14.811709,-6.695149,7.641358,12.263671,-38.653667,-3.170848,...,1.177639,0.770060,1.304632,-2.200233,1.382366,-2.309437,1.451253,-0.410933,3.727620,TCGA-BA-4077-01
4,-23.492684,78.722428,2.399360,22.597803,-5.793599,11.976908,-21.316500,1.220622,-7.008985,-13.086680,...,-0.901368,-1.393148,-1.248257,0.487822,-0.735874,0.863202,-2.340097,-1.454057,-0.908453,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,51.719029,-13.759235,9.603475,-17.378117,36.199802,-6.625736,5.532348,-31.437382,1.696102,0.101085,...,-0.850935,3.275833,-1.396058,1.649309,-3.085578,1.974218,4.267149,4.121220,-0.871404,TCGA-UF-A7JT-01
515,13.009808,-14.443833,24.877834,12.637027,33.381403,-4.012832,-11.003321,-14.842029,9.239174,-18.849358,...,-0.033763,-4.016822,-1.367077,0.021611,1.443175,1.455068,1.277097,-0.733819,0.252996,TCGA-UF-A7JV-01
516,78.470383,55.979789,10.624242,-30.658030,7.747516,-0.823795,-19.008927,24.587056,-10.211918,-5.948767,...,-2.100146,0.436497,-3.223547,-1.649205,-0.273396,-0.626491,1.504990,-0.064966,-0.768826,TCGA-UP-A6WW-01
517,6.350374,5.826974,-12.860726,18.283309,-11.623426,-22.091447,-22.782900,-2.080459,9.482621,6.766271,...,2.332970,-0.309085,4.611991,-2.363892,1.197431,0.285975,-1.579279,0.090064,-0.166647,TCGA-WA-A7GZ-01
518,-11.899501,14.375983,15.114765,13.469000,10.420569,15.140895,-29.565610,0.822404,16.905219,8.566021,...,1.506712,-4.623267,-3.948606,-0.478567,4.060867,0.880036,2.991359,2.692969,-1.227006,TCGA-WA-A7H4-01

In [203]:
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(Z3, y)
importances = rf.feature_importances_
feature_names = [i+1 for i in range(Z3.shape[1])]
importance_df = pd.DataFrame({"Feature": feature_names, "Importance": importances})
importance_df.sort_values("Importance", ascending=False, inplace=True)
selected_features = importance_df["Feature"].head(291)
print("Number of selected features: ", len(selected_features))
print("Selected features: ", selected_features.tolist())

try:
    columns = []
    for i in selected_features:
        column = Z3[:, i]
        columns.append(column)
except Exception:
    pass
Zrf3 = np.column_stack(columns)
#STORING REDUCED DATA TO CSV
nrf3 = pd.DataFrame(Zrf3)
hugo=[]
for i in range(1,520):
    hugo.append(drn['index'][i])
nrf3["Hugo"]=hugo
nrf3

Number of selected features:  291
Selected features:  [275, 270, 2, 298, 254, 318, 258, 1, 22, 158, 114, 141, 308, 274, 320, 301, 193, 46, 312, 3, 98, 165, 195, 168, 60, 117, 52, 283, 302, 10, 236, 317, 285, 221, 240, 291, 267, 91, 321, 190, 94, 115, 227, 202, 156, 13, 145, 242, 179, 300, 88, 228, 124, 182, 205, 200, 23, 255, 304, 132, 307, 102, 138, 5, 266, 67, 263, 43, 8, 169, 28, 197, 272, 303, 42, 249, 30, 116, 222, 229, 4, 89, 64, 226, 230, 79, 66, 31, 174, 81, 105, 273, 125, 299, 313, 12, 257, 84, 262, 142, 37, 287, 181, 118, 58, 186, 27, 214, 110, 251, 18, 311, 204, 162, 180, 323, 170, 148, 73, 237, 271, 143, 38, 192, 63, 164, 137, 305, 33, 314, 167, 243, 232, 294, 113, 173, 50, 218, 99, 32, 278, 155, 104, 133, 48, 292, 241, 248, 244, 21, 106, 26, 281, 72, 196, 231, 215, 183, 157, 199, 120, 246, 75, 15, 219, 198, 288, 265, 154, 14, 260, 256, 35, 209, 203, 71, 316, 44, 7, 54, 238, 39, 166, 70, 289, 61, 296, 83, 151, 250, 269, 139, 109, 282, 126, 45, 253, 235, 127, 49, 310, 9, 322, 20, 123, 212, 150, 144, 259, 261, 153, 36, 17, 309, 90, 187, 201, 149, 245, 101, 74, 160, 276, 280, 55, 175, 315, 194, 213, 177, 136, 264, 41, 216, 147, 224, 82, 80, 6, 171, 62, 185, 86, 286, 68, 140, 208, 100, 112, 163, 93, 131, 51, 69, 96, 25, 172, 277, 189, 293, 207, 290, 279, 57, 284, 135, 297, 268, 128, 19, 87, 176, 152, 146, 239, 108, 76, 56, 223, 129, 211, 97, 29, 295, 111, 225, 247, 107, 103, 306, 122]

,0,1,2,3,4,5,6,7,8,9,...,106,107,108,109,110,111,112,113,114,Hugo
0,-0.480673,-1.528401,-64.180481,0.435341,-0.118544,0.694952,-1.983205,26.140251,-4.840718,-1.566312,...,-28.618584,-1.337771,0.857529,0.534378,16.352260,-0.656425,2.677846,2.279447,1.130001,TCGA-BA-4074-01
1,-1.506644,2.222960,-37.887466,-0.222704,-1.817303,0.137020,2.440097,-12.397041,14.676029,1.377892,...,14.021039,2.497424,6.092613,-3.346534,45.799704,1.406884,0.019744,-10.982196,2.321455,TCGA-BA-4075-01
2,0.103847,1.607794,-25.135064,-1.799141,0.112766,0.659747,3.020527,-16.493333,-7.031177,7.364665,...,-8.789100,-0.719526,1.379137,0.211568,30.708370,0.638819,0.846458,-0.957753,0.072795,TCGA-BA-4076-01
3,-4.041692,-2.418451,3.526023,-0.337781,1.252675,1.382366,0.889764,1.672591,-4.691108,-2.656691,...,-6.438373,1.562011,8.095778,0.193887,22.973296,-1.456073,7.841413,-0.835726,-3.136421,TCGA-BA-4077-01
4,3.057726,-1.029754,2.399360,0.135373,2.496233,-0.735874,-0.163603,78.722428,-9.582857,-1.968149,...,-13.270933,-1.839230,-4.717183,-6.079587,-12.780905,-3.665004,1.002082,-5.640553,-7.472551,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,2.267505,2.612536,9.603475,1.526292,-1.895059,-3.085578,-3.115193,-13.759235,-4.713487,2.799025,...,-2.168017,2.326579,0.086898,-2.418076,-3.570042,3.957542,0.618574,-1.682277,-0.507874,TCGA-UF-A7JT-01
515,-1.161663,0.015361,24.877834,0.492836,1.120405,1.443175,0.279363,-14.443833,-4.324369,12.165159,...,1.333062,2.657925,0.034281,3.313365,3.915131,-1.911571,-5.031916,9.094998,-4.557664,TCGA-UF-A7JV-01
516,-1.040037,-1.633305,10.624242,-2.040297,-4.188121,-0.273396,-4.505330,55.979789,-14.842493,-0.699194,...,1.007195,-1.980406,-1.293709,-2.827508,1.276624,-0.354312,-2.648201,6.482495,-3.159828,TCGA-UP-A6WW-01
517,8.300447,0.645235,-12.860726,-0.145647,-0.512812,1.197431,3.449474,5.826974,0.996653,-5.621055,...,-3.781055,-1.540307,1.044736,-2.319560,-5.108419,0.561623,0.850141,2.925673,0.214934,TCGA-WA-A7GZ-01
518,2.672705,-0.052083,15.114765,0.870027,-5.171678,4.060867,-5.085880,14.375983,-4.283216,0.507093,...,8.072823,4.713571,-2.395588,-1.996406,-12.872495,0.416509,-1.347660,0.214552,-1.479360,TCGA-WA-A7H4-01

In [204]:
lr = LinearRegression()
rfe = RFE(lr, n_features_to_select=291)
rfe.fit(Z3, y)
selected_features = [i+1 for i in range(len(rfe.support_)) if rfe.support_[i]]
print("Selected Features:", selected_features)
try:
    columns = []
    for i in selected_features:
        column = Z3[:, i]
        columns.append(column)
except Exception:
    pass
Zre3 = np.column_stack(columns)
#STORING REDUCED DATA TO CSV
nre3 = pd.DataFrame(Zre3)
hugo=[]
for i in range(1,520):
    hugo.append(drn['index'][i])
nre3["Hugo"]=hugo
nre3

Selected Features: [1, 3, 5, 7, 9, 10, 11, 14, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 44, 45, 46, 47, 48, 49, 51, 53, 54, 55, 56, 57, 58, 59, 60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 82, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 96, 97, 98, 99, 100, 101, 103, 104, 105, 107, 108, 109, 110, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 136, 137, 138, 139, 140, 142, 143, 144, 145, 146, 147, 148, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 193, 194, 195, 196, 197, 198, 199, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 212, 213, 214, 215, 216, 217, 218, 219, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 300, 301, 302, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 316, 317, 318, 319, 320, 321, 322, 323]

,0,1,2,3,4,5,6,7,8,9,...,281,282,283,284,285,286,287,288,289,Hugo
0,26.140251,84.128182,118.150329,59.027978,-3.691583,21.816013,-35.854289,-4.723802,-17.608646,-26.845678,...,0.092756,0.382470,-0.057020,0.325537,0.694952,-0.482477,1.118546,0.213597,-0.696501,TCGA-BA-4074-01
1,-12.397041,67.227723,67.235101,26.330579,-4.606208,11.582840,-6.213369,-37.141295,-10.054701,-6.625457,...,-0.918537,-1.212201,0.412864,0.740884,0.137020,0.459506,-0.777263,-0.180791,0.169482,TCGA-BA-4075-01
2,-16.493333,17.473437,25.737596,15.763583,-14.311950,5.457589,1.417669,-5.934960,-16.142699,11.399890,...,1.314116,1.342636,-0.137815,-2.072257,0.659747,0.066044,1.033133,-1.136326,0.313676,TCGA-BA-4076-01
3,1.672591,-12.276289,-6.695149,12.263671,-3.170848,-4.432494,-1.617482,2.890126,-8.861937,-1.404453,...,-2.556449,1.177639,1.304632,-2.200233,1.382366,-2.309437,1.451253,-0.410933,3.727620,TCGA-BA-4077-01
4,78.722428,22.597803,11.976908,1.220622,-13.086680,16.454448,2.594149,-3.561151,10.785781,-27.568553,...,-2.051982,-0.901368,-1.248257,0.487822,-0.735874,0.863202,-2.340097,-1.454057,-0.908453,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,-13.759235,-17.378117,-6.625736,-31.437382,0.101085,9.640869,-9.117711,8.643019,6.362297,-5.175814,...,-1.325050,-0.850935,-1.396058,1.649309,-3.085578,1.974218,4.267149,4.121220,-0.871404,TCGA-UF-A7JT-01
515,-14.443833,12.637027,-4.012832,-14.842029,-18.849358,-27.275862,0.300411,5.127871,12.110279,-2.033898,...,-2.110815,-0.033763,-1.367077,0.021611,1.443175,1.455068,1.277097,-0.733819,0.252996,TCGA-UF-A7JV-01
516,55.979789,-30.658030,-0.823795,24.587056,-5.948767,-28.453676,20.037001,-26.703515,-16.962199,-2.282956,...,-0.303433,-2.100146,-3.223547,-1.649205,-0.273396,-0.626491,1.504990,-0.064966,-0.768826,TCGA-UP-A6WW-01
517,5.826974,18.283309,-22.091447,-2.080459,6.766271,12.002829,-8.474645,-17.249402,-2.628596,-2.423221,...,-0.469113,2.332970,4.611991,-2.363892,1.197431,0.285975,-1.579279,0.090064,-0.166647,TCGA-WA-A7GZ-01
518,14.375983,13.469000,15.140895,0.822404,8.566021,9.143026,0.431818,3.546957,10.765033,-9.578538,...,3.148045,1.506712,-3.948606,-0.478567,4.060867,0.880036,2.991359,2.692969,-1.227006,TCGA-WA-A7H4-01

In [205]:
en = ElasticNetCV(l1_ratio=0.5, cv=5)
en.fit(Z3, y)
coef = pd.Series(en.coef_, index=[i+1 for i in range(Z3.shape[1])])
selected_features = coef.abs().nlargest(291).index
print("Number of selected features: ", len(selected_features))
print("Selected features: ", selected_features.tolist())
try:
    columns = []
    for i in selected_features:
        column = Z3[:, i]
        columns.append(column)
except Exception:
    pass
Ze3 = np.column_stack(columns)
#STORING REDUCED DATA TO CSV
ne3 = pd.DataFrame(Ze3)
hugo=[]
for i in range(1,520):
    hugo.append(drn['index'][i])
ne3["Hugo"]=hugo
ne3

Number of selected features:  291
Selected features:  [30, 23, 1, 9, 5, 3, 7, 2, 4, 6, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291]

,0,1,2,3,4,5,6,7,8,9,...,282,283,284,285,286,287,288,289,290,Hugo
0,1.747470,20.123539,26.140251,-3.691583,118.150329,84.128182,59.027978,-64.180481,135.132266,53.186133,...,0.162991,0.852575,0.322971,-0.833412,-0.679586,-0.632877,0.557737,0.595701,-0.936562,TCGA-BA-4074-01
1,7.521387,29.372762,-12.397041,-4.606208,67.235101,67.227723,26.330579,-37.887466,89.696953,24.330854,...,1.676380,-0.430615,1.016186,-1.737444,0.873131,-0.708883,2.261758,-1.183149,0.234512,TCGA-BA-4075-01
2,-10.452968,-1.958084,-16.493333,-14.311950,25.737596,17.473437,15.763583,-25.135064,11.606667,-9.259798,...,-0.380931,-0.734615,1.177899,0.358913,0.152509,0.791177,1.818679,0.217971,-1.441645,TCGA-BA-4076-01
3,6.123144,-5.454032,1.672591,-3.170848,-6.695149,-12.276289,12.263671,3.526023,14.811709,7.641358,...,2.651402,2.329614,-0.439670,0.058612,0.663634,-0.717229,1.035346,0.107913,2.615635,TCGA-BA-4077-01
4,1.632842,10.283375,78.722428,-13.086680,11.976908,22.597803,1.220622,2.399360,-5.793599,-21.316500,...,0.571520,2.429129,-0.929571,-0.509388,-1.238542,-0.997626,-1.083347,2.367563,0.578097,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,-1.499456,9.097573,-13.759235,0.101085,-6.625736,-17.378117,-31.437382,9.603475,36.199802,5.532348,...,1.624205,-0.019525,0.469606,0.153028,-1.417392,0.960094,4.833039,-4.107806,1.381685,TCGA-UF-A7JT-01
515,-3.103691,-3.999083,-14.443833,-18.849358,-4.012832,12.637027,-14.842029,24.877834,33.381403,-11.003321,...,3.408855,-3.958462,-0.392053,-0.779298,-0.092702,-2.070277,1.127375,1.978467,0.817876,TCGA-UF-A7JV-01
516,2.633178,6.821034,55.979789,-5.948767,-0.823795,-30.658030,24.587056,10.624242,7.747516,-19.008927,...,-4.903620,1.757902,-0.266796,-0.693369,-0.627940,-0.637565,-0.543259,1.045121,-0.390382,TCGA-UP-A6WW-01
517,-0.740217,15.854177,5.826974,6.766271,-22.091447,18.283309,-2.080459,-12.860726,-11.623426,-22.782900,...,0.312277,-2.979214,0.371831,-3.099098,2.180333,-0.519341,-0.772413,1.845725,-3.432510,TCGA-WA-A7GZ-01
518,2.223088,-3.611551,14.375983,8.566021,15.140895,13.469000,0.822404,15.114765,10.420569,-29.565610,...,2.618044,-1.011191,-0.923827,1.707429,2.405355,0.416403,2.148716,-2.191883,-2.793155,TCGA-WA-A7H4-01

In [206]:
lasso = Lasso(alpha=0.1)  # alpha is the regularization strength
lasso.fit(Z3, y)
n_components = Z3.shape[1]
feature_names = [i+1 for i in range(n_components)]
coef = pd.Series(lasso.coef_, index=feature_names)
selected_features = coef.abs().nlargest(291).index
print("Number of selected features: ", len(selected_features))
print("Selected features: ", selected_features)
try:
    columns = []
    for i in selected_features:
        column = Z3[:, i]
        columns.append(column)
except Exception:
    pass
Zl3 = np.column_stack(columns)
nl3 = pd.DataFrame(Zl3)
hugo=[]
for i in range(1,520):
    hugo.append(drn['index'][i])
nl3["Hugo"]=hugo
nl3

Number of selected features:  291
Selected features:  Int64Index([308, 274, 304, 275, 276, 250, 254, 301, 291, 283,
            ...
             51,  68,  57, 122, 257,  56, 225, 237,  43,  50],
           dtype='int64', length=291)

,0,1,2,3,4,5,6,7,8,9,...,98,99,100,101,102,103,104,105,106,Hugo
0,0.415982,-1.105859,0.176832,-0.480673,-0.041496,-0.103719,-0.118544,-0.615672,-0.936562,0.162991,...,2.354888,3.083025,3.349546,0.357064,12.722577,4.521750,-3.520288,-9.626202,0.631720,TCGA-BA-4074-01
1,0.187910,0.196675,0.214312,-1.506644,1.720218,-1.248384,-1.817303,1.932059,0.234512,1.676380,...,14.464959,-10.135893,-0.807439,-0.535116,0.987753,0.528845,2.278536,-4.551538,-0.069264,TCGA-BA-4075-01
2,-0.377333,1.592701,-0.022279,0.103847,2.558516,-0.714922,0.112766,0.303501,-1.441645,-0.380931,...,-6.833154,7.160722,-13.906895,-0.391644,5.506016,-11.407450,4.936816,12.728534,-1.760901,TCGA-BA-4076-01
3,1.641293,0.187114,-2.086219,-4.041692,2.126098,2.989737,1.252675,3.679153,2.615635,2.651402,...,-2.223732,-5.260920,-1.934917,-7.343385,-0.442012,-3.499604,-0.746591,-5.278018,-1.159292,TCGA-BA-4077-01
4,0.767091,1.837196,-1.065075,3.057726,1.984739,-1.422340,2.496233,-1.550652,0.578097,0.571520,...,-5.862445,4.550931,-8.751847,-0.855586,-9.814050,6.926521,0.877829,6.576755,6.571966,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,-2.317315,2.362812,-0.475713,2.267505,2.523066,-2.710434,-1.895059,0.012682,1.381685,1.624205,...,-0.803231,8.236843,-0.739060,-2.445723,-1.299417,2.363966,-3.129090,0.688498,-0.124857,TCGA-UF-A7JT-01
515,0.457069,-0.309554,0.036848,-1.161663,-2.905006,-1.654441,1.120405,-1.740621,0.817876,3.408855,...,0.405417,-3.331166,-2.837182,-10.459444,-1.289191,-5.532343,2.314712,-1.561796,0.657498,TCGA-UF-A7JV-01
516,-2.910031,1.317221,2.052189,-1.040037,-0.362945,-0.960027,-4.188121,-2.064783,-0.390382,-4.903620,...,-1.962445,7.969327,1.450100,0.153107,-6.951539,2.248474,-7.527209,11.650364,1.544030,TCGA-UP-A6WW-01
517,-3.175107,2.202838,-4.123370,8.300447,0.216092,2.070079,-0.512812,-1.850399,-3.432510,0.312277,...,4.182035,3.304729,8.024892,5.286407,-5.735231,1.784466,-3.322501,9.586676,-1.147876,TCGA-WA-A7GZ-01
518,-1.395599,-1.205769,1.422452,2.672705,2.245551,2.429510,-5.171678,-0.049932,-2.793155,2.618044,...,-0.076880,4.129383,0.855039,0.170066,3.396724,-1.938799,-3.323440,6.194983,-0.193927,TCGA-WA-A7H4-01

In [207]:
df = pd.read_csv("data_linear_CNA.csv")

#DROP ROWS AND COLUMNS
df =df.dropna()
df.drop("Entrez_Gene_Id", axis=1 ,inplace=True)

#SET INDEX
df.set_index('Hugo_Symbol', inplace=True)

#TRANSPOSE ROWS INTO COLUMNS
df5 = df.T
df5.to_csv("CNA.csv")
df5.head()
merged_df = pd.merge(cl, df5, left_index=True, right_index=True, how="inner")
df5=merged_df
c5 = pd.DataFrame(df5)
c5.to_csv("CNApreprocessed.csv")
y = c5['Overall Survival (Months)']
c5 = c5.drop('Overall Survival (Months)', axis=1)
y.drop(y.index[-1], inplace=True)
dcn=c5.iloc[:,:]
#print(d)
dcn = dcn.reset_index()
Cn=dcn.iloc[1:,1:]
Cn.head()
#PCA 
scaler = StandardScaler()
# Fit on training set only.
X4 = scaler.fit_transform(Cn[:])
#fit pca on data
pca = PCA(.95)
pca.fit(X4)
#transform pca
Z4 =pca.transform(X4)
Z4

n4 = pd.DataFrame(Z4)
hugo=[]
for i in range(1,522):
    hugo.append(dcn['index'][i])
n4["Hugo"]=hugo
n4

,0,1,2,3,4,5,6,7,8,9,...,154,155,156,157,158,159,160,161,162,Hugo
0,33.216651,-50.436050,-21.986615,12.885906,11.482549,-24.466906,15.074239,4.380173,5.485482,28.698759,...,-4.221799,5.491535,0.070140,0.487326,2.201151,2.565021,1.753826,3.110208,-4.895575,TCGA-BA-4074-01
1,28.236597,64.891526,-91.108694,-44.133534,-34.305138,22.601760,-7.031638,32.943213,-29.234978,6.485621,...,3.736035,2.225140,-1.163774,-6.966220,-1.753357,3.092001,3.498170,-4.722361,-7.724069,TCGA-BA-4075-01
2,31.712084,-19.142462,-44.955697,-10.915900,19.480211,42.130128,-43.298753,-5.824047,-29.996371,34.289886,...,0.600484,2.803526,0.105918,-0.371706,1.871839,0.090110,1.151674,-0.852966,2.845306,TCGA-BA-4076-01
3,7.214877,2.055477,16.367214,-31.625528,23.580592,55.697236,-6.511316,-2.483694,-2.420799,28.907656,...,1.853797,6.721109,-2.849703,-0.575362,-8.391093,3.360215,-4.075149,-1.944482,4.489747,TCGA-BA-4077-01
4,106.422401,-121.377760,73.987637,-2.817309,61.276928,-18.995732,25.623114,20.360234,25.771941,24.407902,...,8.946784,3.037491,-0.786278,-0.572699,-4.557307,-4.469469,0.572520,-5.672586,-0.230037,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,-40.190795,-5.455551,3.334912,-12.005291,-13.635163,13.930237,15.611677,-7.288980,-1.165533,-4.699541,...,-0.497494,-0.191485,-0.242291,0.418177,1.023733,-0.140109,0.692467,-0.743963,1.400882,TCGA-UF-A7JT-01
517,-43.964526,-1.144883,-6.521891,-4.225571,-18.626533,-11.038020,7.032690,11.173420,-5.910724,-8.290236,...,0.468838,1.506211,2.076427,0.957400,1.842098,1.068540,0.215576,-1.282296,-0.428725,TCGA-UF-A7JV-01
518,-11.735949,-119.457581,53.408786,-3.863532,19.905231,-4.851157,-40.494109,-15.368992,-94.071584,20.233563,...,-5.335174,-1.768149,2.781818,1.492448,-0.837836,-3.482304,-2.590394,-0.523163,3.962935,TCGA-UP-A6WW-01
519,47.663786,-37.292774,-36.082906,-35.697312,-2.236555,-38.248416,-24.300350,23.728644,3.907556,-34.511521,...,7.329330,9.374125,-4.312231,-2.122407,-2.172592,4.312280,-1.897955,6.545917,5.143305,TCGA-WA-A7GZ-01
520,-34.250717,-1.709041,-13.289835,19.932306,-20.826372,-11.613360,13.608435,-8.567912,-0.583031,-5.474946,...,-0.083828,-1.224837,-0.561353,-0.355435,0.746019,-0.305563,-0.349857,-0.895570,-0.691640,TCGA-WA-A7H4-01

In [208]:
lasso = Lasso(alpha=0.1)  # alpha is the regularization strength
lasso.fit(Z4, y)
n_components = Z4.shape[1]
feature_names = [i+1 for i in range(n_components)]
coef = pd.Series(lasso.coef_, index=feature_names)
selected_features = coef.abs().nlargest(144).index
print("Number of selected features: ", len(selected_features))
print("Selected features: ", selected_features)
try:
    columns = []
    for i in selected_features:
        column = Z4[:, i]
        columns.append(column)
except Exception:
    pass
Zl4 = np.column_stack(columns)
nl4 = pd.DataFrame(Zl4)
hugo=[]
for i in range(1,522):
    hugo.append(dcn['index'][i])
nl4["Hugo"]=hugo
nl4

Number of selected features:  144
Selected features:  Int64Index([138, 144, 147, 123, 126, 133, 162, 146, 132, 150,
            ...
             26,  79,  14,  77,  48,  68,  10,   6,  34,   5],
           dtype='int64', length=144)

,0,1,2,3,4,5,6,7,8,9,...,36,37,38,39,40,41,42,43,44,Hugo
0,1.116977,-0.130461,-5.188776,1.477828,-6.640217,2.127256,-4.895575,-8.217427,0.371075,-0.396754,...,-0.852220,-2.504353,-4.221799,-5.997827,3.776924,2.565021,-1.184395,7.747713,3.690759,TCGA-BA-4074-01
1,-4.740436,2.112820,-6.122692,-2.377654,7.718275,6.229768,-7.724069,-3.293444,-4.054897,3.933859,...,-6.770378,0.651014,3.736035,-2.713656,5.783846,3.092001,-1.489265,-8.469626,3.198156,TCGA-BA-4075-01
2,-0.990805,1.713094,1.205956,0.076707,-1.998481,0.534250,2.845306,-1.463883,-1.324598,1.395654,...,-4.355525,0.739403,0.600484,-3.876413,-5.567423,0.090110,3.449468,-0.877048,-1.996506,TCGA-BA-4076-01
3,12.175045,9.908431,8.682547,-6.709406,-12.842134,-6.849539,4.489747,5.204148,-16.519012,2.305126,...,-2.251777,-6.636852,1.853797,-0.702552,2.142546,3.360215,-0.328589,-3.720502,6.238997,TCGA-BA-4077-01
4,4.312326,1.036209,0.669677,-0.746316,10.673486,0.615714,-0.230037,3.974406,-1.912355,4.452021,...,-1.549889,-9.295948,8.946784,-14.862014,-1.325410,-4.469469,-4.996590,-1.675104,4.846861,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,0.132458,-2.388246,1.325539,-2.385219,1.047296,-0.621859,1.400882,-1.686925,0.675235,2.192528,...,2.556182,-1.744148,-0.497494,2.204485,-0.105358,-0.140109,0.859642,-1.156035,-0.800003,TCGA-UF-A7JT-01
517,0.477622,0.745332,1.394929,1.944200,0.004126,0.690237,-0.428725,2.390350,0.562853,-0.011672,...,1.990326,1.039228,0.468838,-0.412742,-1.121266,1.068540,0.143846,-1.685026,1.114145,TCGA-UF-A7JV-01
518,7.171610,-7.204480,-2.297103,-5.076078,1.575399,3.162044,3.962935,-1.191342,-0.336968,-8.618751,...,2.304096,-4.987639,-5.335174,-3.954828,3.779893,-3.482304,4.770948,-1.065132,-14.496394,TCGA-UP-A6WW-01
519,-4.533560,-4.645939,2.869361,11.853858,6.811016,6.586153,5.143305,-1.477893,5.572389,3.116882,...,-1.147557,5.104404,7.329330,-4.336571,-5.090246,4.312280,14.910584,0.743293,-10.924072,TCGA-WA-A7GZ-01
520,0.136811,-0.522102,-0.078921,-0.723861,1.219589,-2.393814,-0.691640,0.177457,0.437999,-0.907496,...,1.610287,0.532311,-0.083828,1.291541,-0.226651,-0.305563,0.251863,-0.538431,0.283602,TCGA-WA-A7H4-01

In [209]:
en = ElasticNetCV(l1_ratio=0.5, cv=5)
en.fit(Z4, y)
coef = pd.Series(en.coef_, index=[i+1 for i in range(Z4.shape[1])])
selected_features = coef.abs().nlargest(144).index
print("Number of selected features: ", len(selected_features))
print("Selected features: ", selected_features.tolist())
try:
    columns = []
    for i in selected_features:
        column = Z4[:, i]
        columns.append(column)
except Exception:
    pass
Ze4 = np.column_stack(columns)
#STORING REDUCED DATA TO CSV
ne4 = pd.DataFrame(Ze4)
hugo=[]
try:
    for i in range(1,522):
        hugo.append(dcn['index'][i])
    ne4["Hugo"]=hugo
except Exception:
    pass

Number of selected features:  144
Selected features:  [2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144]

In [210]:
lr = LinearRegression()
rfe = RFE(lr, n_features_to_select=144)
rfe.fit(Z4, y)
selected_features = [i+1 for i in range(len(rfe.support_)) if rfe.support_[i]]
print("Selected Features:", selected_features)
try:
    columns = []
    for i in selected_features:
        column = Z4[:, i]
        columns.append(column)
except Exception:
    pass
Zre4 = np.column_stack(columns)
#STORING REDUCED DATA TO CSV
nre4 = pd.DataFrame(Zre4)
hugo=[]
try:
    for i in range(1,522):
        hugo.append(dcn['index'][i])
    nre4["Hugo"]=hugo
except Exception:
    pass

Selected Features: [2, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 17, 18, 19, 21, 22, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 95, 96, 97, 98, 99, 100, 101, 102, 103, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 149, 150, 151, 152, 153, 154, 155, 156, 158, 159, 160, 161, 162, 163]

In [211]:
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(Z4, y)
importances = rf.feature_importances_
feature_names = [i+1 for i in range(Z4.shape[1])]
importance_df = pd.DataFrame({"Feature": feature_names, "Importance": importances})
importance_df.sort_values("Importance", ascending=False, inplace=True)
selected_features = importance_df["Feature"].head(144)
print("Number of selected features: ", len(selected_features))
print("Selected features: ", selected_features.tolist())

try:
    columns = []
    for i in selected_features:
        column = Z4[:, i]
        columns.append(column)
except Exception:
    pass
Zrf4 = np.column_stack(columns)
#STORING REDUCED DATA TO CSV
nrf4 = pd.DataFrame(Zrf4)
hugo=[]
for i in range(1,522):
    hugo.append(dcn['index'][i])
nrf4["Hugo"]=hugo
nrf4

Number of selected features:  144
Selected features:  [138, 119, 147, 57, 127, 28, 146, 123, 111, 155, 2, 131, 78, 92, 55, 60, 31, 136, 161, 69, 18, 158, 44, 9, 144, 13, 36, 7, 105, 151, 116, 149, 84, 39, 97, 125, 124, 1, 157, 135, 160, 29, 11, 112, 98, 25, 33, 133, 106, 66, 148, 43, 5, 4, 91, 150, 95, 16, 63, 52, 90, 162, 48, 100, 34, 12, 94, 15, 129, 56, 46, 40, 27, 58, 59, 30, 156, 50, 101, 126, 159, 108, 14, 141, 51, 19, 75, 6, 132, 70, 114, 22, 41, 82, 103, 53, 153, 23, 8, 74, 102, 3, 145, 77, 154, 76, 20, 93, 85, 65, 96, 118, 64, 67, 83, 21, 152, 121, 110, 81, 37, 120, 107, 49, 117, 134, 38, 42, 104, 140, 130, 68, 45, 79, 72, 71, 99, 115, 24, 17, 122, 88, 142, 32]

,0,1,2,3,4,5,6,7,8,9,...,135,136,137,138,139,140,141,142,143,Hugo
0,1.116977,-0.117704,-5.188776,-0.275892,3.233952,-23.880077,-8.217427,1.477828,-0.852220,5.491535,...,6.551635,1.997417,-2.504353,15.273645,13.104654,-1.285523,-3.576617,2.247761,-1.591894,TCGA-BA-4074-01
1,-4.740436,-2.598984,-6.122692,-8.918632,-15.395690,-45.140034,-3.293444,-2.377654,-6.770378,2.225140,...,9.564178,-7.396187,0.651014,23.988777,25.627189,3.569625,1.926271,-1.533819,-9.875864,TCGA-BA-4075-01
2,-0.990805,-2.392617,1.205956,21.363742,-6.478793,4.056920,-1.463883,0.076707,-4.355525,2.803526,...,-20.768423,-0.727165,0.739403,-25.833778,-35.641362,5.793076,28.821208,-0.075137,33.708866,TCGA-BA-4076-01
3,12.175045,5.695712,8.682547,-16.109201,-11.465643,27.035562,5.204148,-6.709406,-2.251777,6.721109,...,-10.039116,6.643813,-6.636852,-2.247810,-11.776269,-8.179908,14.557527,2.451749,13.346500,TCGA-BA-4077-01
4,4.312326,6.248594,0.669677,-9.510697,-1.311870,-3.693250,3.974406,-0.746316,-1.549889,3.037491,...,-0.450101,-6.898493,-9.295948,-51.379379,49.748527,-10.938452,4.027489,3.895741,-21.791770,TCGA-BA-4078-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,0.132458,-0.439050,1.325539,2.245459,3.208296,-2.185221,-1.686925,-2.385219,2.556182,-0.191485,...,1.774241,1.615764,-1.744148,7.883323,-2.890665,-1.527535,0.741717,0.251224,1.429226,TCGA-UF-A7JT-01
517,0.477622,-3.026826,1.394929,2.887661,-0.232177,-2.834909,2.390350,1.944200,1.990326,1.506211,...,-2.315342,3.408189,1.039228,0.298348,5.621048,1.175532,-2.809848,-3.456209,11.383814,TCGA-UF-A7JV-01
518,7.171610,2.254774,-2.297103,10.492162,-2.654302,-34.445437,-1.191342,-5.076078,2.304096,-1.768149,...,1.599634,15.057057,-4.987639,5.380157,-11.008504,0.994211,4.413042,3.216269,-18.868982,TCGA-UP-A6WW-01
519,-4.533560,4.702243,2.869361,17.213804,4.656700,8.197405,-1.477893,11.853858,-1.147557,9.374125,...,8.703422,4.095328,5.104404,-0.097021,20.262528,7.302131,-2.682650,3.578019,-2.992172,TCGA-WA-A7GZ-01
520,0.136811,-1.119680,-0.078921,2.148305,-0.420679,5.969499,0.177457,-0.723861,1.610287,-1.224837,...,0.192250,-0.042218,0.532311,2.156829,-6.634942,-0.307811,1.251797,1.550182,-0.117677,TCGA-WA-A7H4-01

Merging dataset

In [212]:
z=[]
x=[]

for i in range(0,527):
    for j in range(0,519):
        if(n1['Hugo'][i]==n3['Hugo'][j]):
            z.append(n1['Hugo'][i])
for i in range(0,len(z)):
    for j in range(0,520):
        if(z[i]==n4['Hugo'][j]):
            x.append(z[i])

dfmerge = pd.DataFrame()
dfmerge['Hugo']=x

mdf=pd.merge(dfmerge,n1,on='Hugo')
mdf=pd.merge(mdf,n3,on='Hugo')
mdf=pd.merge(mdf,n4,on='Hugo')

mdf = pd.DataFrame(mdf)
cl=pd.read_csv('CLINICALpreprocessed.CSV')
intersect= set.intersection(set(cl.index),set(mdf.index))
set(mdf.index)-intersect
for i in (set(mdf.index)-intersect):
    mdf.drop(i,inplace=True)
for i in (set(cl.index)-intersect):
    cl.drop(i,inplace=True)

cl.drop("Patient Identifier", axis=1,inplace=True)


print(cl.shape)
print(mdf.shape)
mdf=pd.concat([mdf,cl],axis=1)
mdf.drop("Hugo", axis=1,inplace=True)
mdf.columns = mdf.columns.astype(str)
scaler=per.MinMaxScaler(feature_range=(0,1))
rescaleData=scaler.fit_transform(mdf)
mdf=pd.DataFrame(rescaleData,index=mdf.index,columns=mdf.columns)
mdf.head()
df_train = mdf
df_test = df_train.sample(frac=0.3)
X_test=df_test
df_train = df_train.drop(df_test.index)
df_val = df_train.sample(frac=0.2)
X_train=df_train = df_train.drop(df_val.index)
df_train
get_target = lambda df: (df['Overall Survival (Months)'].values)
Y_train = get_target(df_train)

Y_test = get_target(df_test)
get_target = lambda df: (df['Overall Survival Status'].values)
E_train = get_target(df_train)
E_test = get_target(df_test)

# Exclude non-numeric columns from X_train and X_test
X_train_numeric = X_train.select_dtypes(include=[np.number])
X_test_numeric = X_test.select_dtypes(include=[np.number])
n_features = X_train.shape[1]
n_patients_train = X_train.shape[0]


# Drop columns containing string values from X_train and X_test
columns_to_drop = X_train.columns[X_train.applymap(type).eq(str).any()]
if 'Hugo' in columns_to_drop:
    columns_to_drop = columns_to_drop.drop('Hugo')

X_train_numeric = X_train_numeric.drop(columns=columns_to_drop, errors='ignore')
X_test_numeric = X_test_numeric.drop(columns=columns_to_drop, errors='ignore')

# Sorting
sort_idx = np.argsort(Y_train)[::-1]

# Use array indexing to select rows based on sort_idx
X_train_sorted = X_train_numeric.iloc[sort_idx, :]
Y_train_sorted = Y_train[sort_idx]


dsk = deepsurvk.DeepSurvK(n_features=n_features, E=E_train,)
callbacks = deepsurvk.common_callbacks()
print(callbacks)

epochs = 30
history = dsk.fit(X_train, Y_train, 
                  batch_size=n_patients_train,
                  epochs=epochs, 
                  callbacks=callbacks,
                  shuffle=False)
Y_pred_train = np.exp(-dsk.predict(X_train))
c_index_train = deepsurvk.concordance_index(Y_train, Y_pred_train, E_train)
print("DEEPSURV")
print(f"c-index of training dataset = {c_index_train}")

Y_pred_test = np.exp(-dsk.predict(X_test))
c_index_test = deepsurvk.concordance_index(Y_test, Y_pred_test, E_test)
print(f"c-index of testing dataset = {c_index_test}")
Y_pred_trainn = (-dsk.predict(X_train))
Y_pred_testt = (-dsk.predict(X_test))

from sklearn.metrics import mean_squared_error
mse=mean_squared_error(Y_test,Y_pred_testt)

import math
rmse=math.sqrt(mse)

from sklearn.metrics import mean_absolute_error 
mae=mean_absolute_error (Y_test,Y_pred_testt)

from sklearn.metrics import median_absolute_error
mdae=median_absolute_error (Y_test,Y_pred_testt)

print("mse=",mse)
print("rmse=",rmse)
print("mae=",mae)
print("mdae=",mdae)

(512, 26)
(512, 874)
[<keras.callbacks.EarlyStopping object at 0x00000187895B7A60>, <keras.callbacks.ModelCheckpoint object at 0x00000187895B7940>]
Epoch 1/30
1/1 [==============================] - 1s 904ms/step - loss: 209489.6562
Epoch 2/30
1/1 [==============================] - 0s 72ms/step - loss: 182508.7500
Epoch 3/30
1/1 [==============================] - 0s 57ms/step - loss: 168447.6875
Epoch 4/30
1/1 [==============================] - 0s 38ms/step - loss: 172445.0312
Epoch 5/30
1/1 [==============================] - 0s 21ms/step - loss: 168523.7812
Epoch 6/30
1/1 [==============================] - 0s 65ms/step - loss: 160660.5938
Epoch 7/30
1/1 [==============================] - 0s 23ms/step - loss: 162241.7031
Epoch 8/30
1/1 [==============================] - 0s 21ms/step - loss: 167010.8125
Epoch 9/30
1/1 [==============================] - 0s 25ms/step - loss: 164389.1250
Epoch 10/30
1/1 [==============================] - 0s 70ms/step - loss: 159940.5625
Epoch 11/30
1/1 [==============================] - 0s 23ms/step - loss: 162395.6562
Epoch 12/30
1/1 [==============================] - 0s 21ms/step - loss: 163659.9375
Epoch 13/30
1/1 [==============================] - 0s 69ms/step - loss: 156556.9688
Epoch 14/30
1/1 [==============================] - 0s 68ms/step - loss: 155858.8906
Epoch 15/30
1/1 [==============================] - 0s 67ms/step - loss: 155212.5469
Epoch 16/30
1/1 [==============================] - 0s 56ms/step - loss: 150403.0469
Epoch 17/30
1/1 [==============================] - 0s 73ms/step - loss: 147326.7656
Epoch 18/30
1/1 [==============================] - 0s 72ms/step - loss: 141256.8438
Epoch 19/30
1/1 [==============================] - 0s 23ms/step - loss: 141683.4844
Epoch 20/30
1/1 [==============================] - 0s 22ms/step - loss: 142709.1562
Epoch 21/30
1/1 [==============================] - 0s 76ms/step - loss: 140724.9375
Epoch 22/30
1/1 [==============================] - 0s 86ms/step - loss: 138221.9062
Epoch 23/30
1/1 [==============================] - 0s 72ms/step - loss: 134427.4531
Epoch 24/30
1/1 [==============================] - 0s 67ms/step - loss: 132540.8281
Epoch 25/30
1/1 [==============================] - 0s 35ms/step - loss: 135707.1094
Epoch 26/30
1/1 [==============================] - 0s 67ms/step - loss: 131407.6406
Epoch 27/30
1/1 [==============================] - 0s 68ms/step - loss: 125346.3047
Epoch 28/30
1/1 [==============================] - 0s 25ms/step - loss: 130587.0234
Epoch 29/30
1/1 [==============================] - 0s 21ms/step - loss: 131402.2812
Epoch 30/30
1/1 [==============================] - 0s 25ms/step - loss: 133824.9062
DEEPSURV
c-index of training dataset = 0.8047836305820545
c-index of testing dataset = 0.8016528925619835
mse= 56.30868254705821
rmse= 7.5039111499975935
mae= 7.330801412743691
mdae= 7.879328586440436

In [213]:
import deepsurvk

dsk = deepsurvk.DeepSurvK(n_features=n_features, E=E_train,)
callbacks = deepsurvk.common_callbacks()
print(callbacks)

epochs = 20
history = dsk.fit(X_train, Y_train, 
                  batch_size=n_patients_train,
                  epochs=epochs, 
                  callbacks=callbacks,
                  shuffle=False)
Y_pred_train = np.exp(-dsk.predict(X_train))
c_index_train = deepsurvk.concordance_index(Y_train, Y_pred_train, E_train)
print("DEEPSURV")
print(f"c-index of training dataset = {c_index_train}")

Y_pred_test = np.exp(-dsk.predict(X_test))
c_index_test = deepsurvk.concordance_index(Y_test, Y_pred_test, E_test)
print(f"c-index of testing dataset = {c_index_test}")
Y_pred_trainn = (-dsk.predict(X_train))
Y_pred_testt = (-dsk.predict(X_test))

from sklearn.metrics import mean_squared_error
mse=mean_squared_error(Y_test,Y_pred_testt)

import math
rmse=math.sqrt(mse)

from sklearn.metrics import mean_absolute_error 
mae=mean_absolute_error (Y_test,Y_pred_testt)

from sklearn.metrics import median_absolute_error
mdae=median_absolute_error (Y_test,Y_pred_testt)

print("mse=",mse)
print("rmse=",rmse)
print("mae=",mae)
print("mdae=",mdae)

[<keras.callbacks.EarlyStopping object at 0x0000018788E91640>, <keras.callbacks.ModelCheckpoint object at 0x0000018788E91940>]
Epoch 1/20
1/1 [==============================] - 1s 1s/step - loss: 197155.0938
Epoch 2/20
1/1 [==============================] - 0s 66ms/step - loss: 178205.9062
Epoch 3/20
1/1 [==============================] - 0s 82ms/step - loss: 178137.4219
Epoch 4/20
1/1 [==============================] - 0s 58ms/step - loss: 171126.3906
Epoch 5/20
1/1 [==============================] - 0s 86ms/step - loss: 170776.5938
Epoch 6/20
1/1 [==============================] - 0s 24ms/step - loss: 173385.5156
Epoch 7/20
1/1 [==============================] - 0s 69ms/step - loss: 163977.6875
Epoch 8/20
1/1 [==============================] - 0s 33ms/step - loss: 174036.5156
Epoch 9/20
1/1 [==============================] - 0s 83ms/step - loss: 162879.7656
Epoch 10/20
1/1 [==============================] - 0s 69ms/step - loss: 156965.0625
Epoch 11/20
1/1 [==============================] - 0s 23ms/step - loss: 157287.8438
Epoch 12/20
1/1 [==============================] - 0s 27ms/step - loss: 158423.9531
Epoch 13/20
1/1 [==============================] - 0s 73ms/step - loss: 149948.0156
Epoch 14/20
1/1 [==============================] - 0s 64ms/step - loss: 146884.3594
Epoch 15/20
1/1 [==============================] - 0s 32ms/step - loss: 149618.8594
Epoch 16/20
1/1 [==============================] - 0s 19ms/step - loss: 149568.8906
Epoch 17/20
1/1 [==============================] - 0s 87ms/step - loss: 146426.0938
Epoch 18/20
1/1 [==============================] - 0s 80ms/step - loss: 141084.0312
Epoch 19/20
1/1 [==============================] - 0s 61ms/step - loss: 140544.4062
Epoch 20/20
1/1 [==============================] - 0s 107ms/step - loss: 136912.3438
DEEPSURV
c-index of training dataset = 0.8110972855891977
c-index of testing dataset = 0.8028335301062574
mse= 30.163096813149853
rmse= 5.4920940280688795
mae= 5.355871892681653
mdae= 5.681370346304293

In [214]:
param_grid = {
    "C": [0.1, 1, 10],
    "kernel": ["linear", "rbf", "poly"],
    "degree": [2, 3, 4],
    "epsilon": [0.01, 0.1, 1],
    "gamma": ["scale", "auto"]
}

svr = SVR()
grid_search = GridSearchCV(svr, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
print("SVR")
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
print("R-squared: ", r2)

SVR
C-index:  0.7781929347826086
Mean squared error:  0.009510094967830106
Mean absolute error:  0.06704002406453081
Median absolute error:  0.049556119028439594
R-squared:  0.5044935556457659

In [215]:
param_grid = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.01, 0.1, 1],
    "max_depth": [1, 2, 3, 4]
}
xgb = XGBRegressor()
grid_search = GridSearchCV(xgb, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("XGBOOST")
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)

XGBOOST
C-index:  0.9813179347826086
Mean squared error:  0.00023259626729466455
R-squared:  0.9878809885950547
c_index: 0.9813179347826086
Mean absolute error:  0.0049472265628325695
Median absolute error:  0.0018317958145069573

In [216]:
param_grid = {
    "n_estimators": [50, 100],
    "learning_rate": [0.01, 0.1],
    "base_estimator__max_depth": [1, 2]
}
base_estimator = DecisionTreeRegressor()
adaboost = AdaBoostRegressor(base_estimator=base_estimator)
grid_search = GridSearchCV(adaboost, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)

G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

C-index:  0.9086701766304348
Mean squared error:  0.001091371912635894
R-squared:  0.9431360235909736
c_index: 0.9086701766304348
Mean absolute error:  0.02682829832135826
Median absolute error:  0.028262490501387173

In [217]:
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, Y_train)
y_pred = rf.predict(X_test)

mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)

C-index:  0.994735054347826
Mean squared error:  0.0003768093460662712
R-squared:  0.9803670247352594
c_index: 0.994735054347826
Mean absolute error:  0.006514807437982906
Median absolute error:  0.0015315080193603683

In [218]:
z=[]
x=[]

for i in range(0,527):
    for j in range(0,519):
        if(nl1['Hugo'][i]==nl3['Hugo'][j]):
            z.append(nl1['Hugo'][i])
for i in range(0,len(z)):
    for j in range(0,520):
        if(z[i]==nl4['Hugo'][j]):
            x.append(z[i])

dfmerge = pd.DataFrame()
dfmerge['Hugo']=x

mdf=pd.merge(dfmerge,nl1,on='Hugo')
mdf=pd.merge(mdf,nl3,on='Hugo')
mdf=pd.merge(mdf,nl4,on='Hugo')

mdf = pd.DataFrame(mdf)
cl=pd.read_csv('CLINICALpreprocessed.CSV')
intersect= set.intersection(set(cl.index),set(mdf.index))
set(mdf.index)-intersect
for i in (set(mdf.index)-intersect):
    mdf.drop(i,inplace=True)
for i in (set(cl.index)-intersect):
    cl.drop(i,inplace=True)

cl.drop("Patient Identifier", axis=1,inplace=True)


print(cl.shape)
print(mdf.shape)
mdf=pd.concat([mdf,cl],axis=1)
mdf.drop("Hugo", axis=1,inplace=True)
mdf.columns = mdf.columns.astype(str)
scaler=per.MinMaxScaler(feature_range=(0,1))
rescaleData=scaler.fit_transform(mdf)
mdf=pd.DataFrame(rescaleData,index=mdf.index,columns=mdf.columns)
mdf.head()
df_train = mdf
df_test = df_train.sample(frac=0.3)
X_test=df_test
df_train = df_train.drop(df_test.index)
df_val = df_train.sample(frac=0.2)
X_train=df_train = df_train.drop(df_val.index)
df_train
get_target = lambda df: (df['Overall Survival (Months)'].values)
Y_train = get_target(df_train)

Y_test = get_target(df_test)
get_target = lambda df: (df['Overall Survival Status'].values)
E_train = get_target(df_train)
E_test = get_target(df_test)

# Exclude non-numeric columns from X_train and X_test
X_train_numeric = X_train.select_dtypes(include=[np.number])
X_test_numeric = X_test.select_dtypes(include=[np.number])
n_features = X_train.shape[1]
n_patients_train = X_train.shape[0]


# Drop columns containing string values from X_train and X_test
columns_to_drop = X_train.columns[X_train.applymap(type).eq(str).any()]
if 'Hugo' in columns_to_drop:
    columns_to_drop = columns_to_drop.drop('Hugo')

X_train_numeric = X_train_numeric.drop(columns=columns_to_drop, errors='ignore')
X_test_numeric = X_test_numeric.drop(columns=columns_to_drop, errors='ignore')

# Sorting
sort_idx = np.argsort(Y_train)[::-1]

# Use array indexing to select rows based on sort_idx
X_train_sorted = X_train_numeric.iloc[sort_idx, :]
Y_train_sorted = Y_train[sort_idx]


dsk = deepsurvk.DeepSurvK(n_features=n_features, E=E_train,)
callbacks = deepsurvk.common_callbacks()
print(callbacks)

epochs = 10
history = dsk.fit(X_train, Y_train, 
                  batch_size=n_patients_train,
                  epochs=epochs, 
                  callbacks=callbacks,
                  shuffle=False)
Y_pred_train = np.exp(-dsk.predict(X_train))
c_index_train = deepsurvk.concordance_index(Y_train, Y_pred_train, E_train)
print("DeepSurv)")
print(f"c-index of training dataset = {c_index_train}")

Y_pred_test = np.exp(-dsk.predict(X_test))
c_index_test = deepsurvk.concordance_index(Y_test, Y_pred_test, E_test)
print(f"c-index of testing dataset = {c_index_test}")
Y_pred_trainn = (-dsk.predict(X_train))
Y_pred_testt = (-dsk.predict(X_test))

from sklearn.metrics import mean_squared_error
mse=mean_squared_error(Y_test,Y_pred_testt)

import math
rmse=math.sqrt(mse)

from sklearn.metrics import mean_absolute_error 
mae=mean_absolute_error (Y_test,Y_pred_testt)

from sklearn.metrics import median_absolute_error
mdae=median_absolute_error (Y_test,Y_pred_testt)

print("mse=",mse)
print("rmse=",rmse)
print("mae=",mae)
print("mdae=",mdae)

(512, 26)
(512, 158)
[<keras.callbacks.EarlyStopping object at 0x0000018786667520>, <keras.callbacks.ModelCheckpoint object at 0x0000018786AA9B50>]
Epoch 1/10
1/1 [==============================] - 1s 825ms/step - loss: 222895.7500
Epoch 2/10
1/1 [==============================] - 0s 46ms/step - loss: 171418.5469
Epoch 3/10
1/1 [==============================] - 0s 31ms/step - loss: 165959.6094
Epoch 4/10
1/1 [==============================] - 0s 49ms/step - loss: 156389.8281
Epoch 5/10
1/1 [==============================] - 0s 0s/step - loss: 164297.8594
Epoch 6/10
1/1 [==============================] - 0s 58ms/step - loss: 153678.6875
Epoch 7/10
1/1 [==============================] - 0s 45ms/step - loss: 150082.3594
Epoch 8/10
1/1 [==============================] - 0s 42ms/step - loss: 149253.9062
Epoch 9/10
1/1 [==============================] - 0s 51ms/step - loss: 146576.0312
Epoch 10/10
1/1 [==============================] - 0s 9ms/step - loss: 147600.9062
DeepSurv)
c-index of training dataset = 0.7767840419554224
c-index of testing dataset = 0.7626550452564532
mse= 0.5661715681265138
rmse= 0.7524437308706305
mae= 0.720862219410834
mdae= 0.7025247291373926

In [219]:
result = np.zeros((5, 4, 5))

result[0][0][0]=c_index_test
result[0][0][1]=mse
result[0][0][2]=rmse
result[0][0][3]=mae
result[0][0][4]=mdae

In [220]:
param_grid = {
    "C": [0.1, 1, 10],
    "kernel": ["linear", "rbf", "poly"],
    "degree": [2, 3, 4],
    "epsilon": [0.01, 0.1, 1],
    "gamma": ["scale", "auto"]
}

svr = SVR()
grid_search = GridSearchCV(svr, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
print("SVR")
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
print("R-squared: ", r2)
result[1][0][0]=c_index
result[1][0][1]=mse
result[1][0][2]=r2
result[1][0][3]=mae
result[1][0][4]=mdae

SVR
C-index:  0.9418960244648318
Mean squared error:  0.0003369988656214718
Mean absolute error:  0.013567099124632574
Median absolute error:  0.010050787397659107
R-squared:  0.9836839758553155

In [221]:
param_grid = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.01, 0.1, 1],
    "max_depth": [1, 2, 3, 4]
}
xgb = XGBRegressor()
grid_search = GridSearchCV(xgb, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("XGBOOST")
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[2][0][0]=c_index
result[2][0][1]=mse
result[2][0][2]=r2
result[2][0][3]=mae
result[2][0][4]=mdae

XGBOOST
C-index:  0.9888718994223581
Mean squared error:  0.00024601339336072545
R-squared:  0.9880890979897304
c_index: 0.9888718994223581
Mean absolute error:  0.0044644587694833695
Median absolute error:  0.0020073139874537283

In [222]:
param_grid = {
    "n_estimators": [50, 100],
    "learning_rate": [0.01, 0.1],
    "base_estimator__max_depth": [1, 2]
}
base_estimator = DecisionTreeRegressor()
adaboost = AdaBoostRegressor(base_estimator=base_estimator)
grid_search = GridSearchCV(adaboost, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[3][0][0]=c_index
result[3][0][1]=mse
result[3][0][2]=r2
result[3][0][3]=mae
result[3][0][4]=mdae

G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

C-index:  0.8873598369011213
Mean squared error:  0.0014097673527668402
R-squared:  0.9317451762820828
c_index: 0.8873598369011213
Mean absolute error:  0.027301306430009064
Median absolute error:  0.02458990324137074

In [223]:
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, Y_train)
y_pred = rf.predict(X_test)

mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[4][0][0]=c_index
result[4][0][1]=mse
result[4][0][2]=r2
result[4][0][3]=mae
result[4][0][4]=mdae

C-index:  0.9966021066938499
Mean squared error:  0.0007018774563922825
R-squared:  0.9660181362807041
c_index: 0.9966021066938499
Mean absolute error:  0.004832476529828711
Median absolute error:  0.0011174907468916966

In [224]:
z=[]
x=[]

for i in range(0,527):
    for j in range(0,519):
        if(ne1['Hugo'][i]==ne3['Hugo'][j]):
            z.append(ne1['Hugo'][i])
for i in range(0,len(z)):
    for j in range(0,520):
        if(z[i]==ne4['Hugo'][j]):
            x.append(z[i])

dfmerge = pd.DataFrame()
dfmerge['Hugo']=x

mdf=pd.merge(dfmerge,ne1,on='Hugo')
mdf=pd.merge(mdf,ne3,on='Hugo')
mdf=pd.merge(mdf,ne4,on='Hugo')

mdf = pd.DataFrame(mdf)
cl=pd.read_csv('CLINICALpreprocessed.CSV')
intersect= set.intersection(set(cl.index),set(mdf.index))
set(mdf.index)-intersect
for i in (set(mdf.index)-intersect):
    mdf.drop(i,inplace=True)
for i in (set(cl.index)-intersect):
    cl.drop(i,inplace=True)

cl.drop("Patient Identifier", axis=1,inplace=True)


print(cl.shape)
print(mdf.shape)
mdf=pd.concat([mdf,cl],axis=1)
mdf.drop("Hugo", axis=1,inplace=True)
mdf.columns = mdf.columns.astype(str)
scaler=per.MinMaxScaler(feature_range=(0,1))
rescaleData=scaler.fit_transform(mdf)
mdf=pd.DataFrame(rescaleData,index=mdf.index,columns=mdf.columns)
mdf.head()
df_train = mdf
df_test = df_train.sample(frac=0.3)
X_test=df_test
df_train = df_train.drop(df_test.index)
df_val = df_train.sample(frac=0.2)
X_train=df_train = df_train.drop(df_val.index)
df_train
get_target = lambda df: (df['Overall Survival (Months)'].values)
Y_train = get_target(df_train)

Y_test = get_target(df_test)
get_target = lambda df: (df['Overall Survival Status'].values)
E_train = get_target(df_train)
E_test = get_target(df_test)

# Exclude non-numeric columns from X_train and X_test
X_train_numeric = X_train.select_dtypes(include=[np.number])
X_test_numeric = X_test.select_dtypes(include=[np.number])
n_features = X_train.shape[1]
n_patients_train = X_train.shape[0]


# Drop columns containing string values from X_train and X_test
columns_to_drop = X_train.columns[X_train.applymap(type).eq(str).any()]
if 'Hugo' in columns_to_drop:
    columns_to_drop = columns_to_drop.drop('Hugo')

X_train_numeric = X_train_numeric.drop(columns=columns_to_drop, errors='ignore')
X_test_numeric = X_test_numeric.drop(columns=columns_to_drop, errors='ignore')

# Sorting
sort_idx = np.argsort(Y_train)[::-1]

# Use array indexing to select rows based on sort_idx
X_train_sorted = X_train_numeric.iloc[sort_idx, :]
Y_train_sorted = Y_train[sort_idx]


dsk = deepsurvk.DeepSurvK(n_features=n_features, E=E_train,)
callbacks = deepsurvk.common_callbacks()
print(callbacks)

epochs = 20
history = dsk.fit(X_train, Y_train, 
                  batch_size=n_patients_train,
                  epochs=epochs, 
                  callbacks=callbacks,
                  shuffle=False)
Y_pred_train = np.exp(-dsk.predict(X_train))
c_index_train = deepsurvk.concordance_index(Y_train, Y_pred_train, E_train)
print("DeepSurv")
print(f"c-index of training dataset = {c_index_train}")

Y_pred_test = np.exp(-dsk.predict(X_test))
c_index_test = deepsurvk.concordance_index(Y_test, Y_pred_test, E_test)
print(f"c-index of testing dataset = {c_index_test}")
Y_pred_trainn = (-dsk.predict(X_train))
Y_pred_testt = (-dsk.predict(X_test))

from sklearn.metrics import mean_squared_error
mse=mean_squared_error(Y_test,Y_pred_testt)

import math
rmse=math.sqrt(mse)

from sklearn.metrics import mean_absolute_error 
mae=mean_absolute_error (Y_test,Y_pred_testt)

from sklearn.metrics import median_absolute_error
mdae=median_absolute_error (Y_test,Y_pred_testt)

print("mse=",mse)
print("rmse=",rmse)
print("mae=",mae)
print("mdae=",mdae)
result[0][1][0]=c_index_test
result[0][1][1]=mse
result[0][1][2]=rmse
result[0][1][3]=mae
result[0][1][4]=mdae

(512, 26)
(512, 782)
[<keras.callbacks.EarlyStopping object at 0x000001878665D160>, <keras.callbacks.ModelCheckpoint object at 0x000001878665D370>]
Epoch 1/20
1/1 [==============================] - 1s 875ms/step - loss: 185078.5156
Epoch 2/20
1/1 [==============================] - 0s 59ms/step - loss: 171763.5156
Epoch 3/20
1/1 [==============================] - 0s 68ms/step - loss: 166328.7500
Epoch 4/20
1/1 [==============================] - 0s 61ms/step - loss: 162692.0781
Epoch 5/20
1/1 [==============================] - 0s 25ms/step - loss: 165025.6250
Epoch 6/20
1/1 [==============================] - 0s 79ms/step - loss: 156833.2812
Epoch 7/20
1/1 [==============================] - 0s 21ms/step - loss: 159343.6094
Epoch 8/20
1/1 [==============================] - 0s 60ms/step - loss: 154521.1875
Epoch 9/20
1/1 [==============================] - 0s 49ms/step - loss: 152515.9219
Epoch 10/20
1/1 [==============================] - 0s 33ms/step - loss: 153247.3906
Epoch 11/20
1/1 [==============================] - 0s 59ms/step - loss: 149809.8594
Epoch 12/20
1/1 [==============================] - 0s 59ms/step - loss: 145340.8594
Epoch 13/20
1/1 [==============================] - 0s 25ms/step - loss: 147245.1719
Epoch 14/20
1/1 [==============================] - 0s 67ms/step - loss: 142830.5781
Epoch 15/20
1/1 [==============================] - 0s 64ms/step - loss: 142437.5781
Epoch 16/20
1/1 [==============================] - 0s 57ms/step - loss: 141953.4844
Epoch 17/20
1/1 [==============================] - 0s 52ms/step - loss: 141542.6406
Epoch 18/20
1/1 [==============================] - 0s 71ms/step - loss: 135132.1875
Epoch 19/20
1/1 [==============================] - 0s 15ms/step - loss: 135781.7031
Epoch 20/20
1/1 [==============================] - 0s 57ms/step - loss: 132373.2656
DeepSurv
c-index of training dataset = 0.8211064064801178
c-index of testing dataset = 0.8294488188976378
mse= 1.8936278430926838
rmse= 1.3760915097088142
mae= 1.1922757809170341
mdae= 1.1548205503105518

In [225]:
param_grid = {
    "C": [0.1, 1, 10],
    "kernel": ["linear", "rbf", "poly"],
    "degree": [2, 3, 4],
    "epsilon": [0.01, 0.1, 1],
    "gamma": ["scale", "auto"]
}

svr = SVR()
grid_search = GridSearchCV(svr, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
print("SVR")
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
print("R-squared: ", r2)
result[1][1][0]=c_index
result[1][1][1]=mse
result[1][1][2]=r2
result[1][1][3]=mae
result[1][1][4]=mdae

SVR
C-index:  0.7673431264328776
Mean squared error:  0.010648497346508079
Mean absolute error:  0.06359396642849147
Median absolute error:  0.045526672787718145
R-squared:  0.48846922041943397

In [226]:
param_grid = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.01, 0.1, 1],
    "max_depth": [1, 2, 3, 4]
}
xgb = XGBRegressor()
grid_search = GridSearchCV(xgb, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("XGBOOST")
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[2][1][0]=c_index
result[2][1][1]=mse
result[2][1][2]=r2
result[2][1][3]=mae
result[2][1][4]=mdae

XGBOOST
C-index:  0.9904899380147746
Mean squared error:  0.00024200302705715916
R-squared:  0.9883746980383106
c_index: 0.9904899380147746
Mean absolute error:  0.004104175939793671
Median absolute error:  0.0015617170296605897

In [227]:
param_grid = {
    "n_estimators": [50, 100],
    "learning_rate": [0.01, 0.1],
    "base_estimator__max_depth": [1, 2]
}
base_estimator = DecisionTreeRegressor()
adaboost = AdaBoostRegressor(base_estimator=base_estimator)
grid_search = GridSearchCV(adaboost, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[3][1][0]=c_index
result[3][1][1]=mse
result[3][1][2]=r2
result[3][1][3]=mae
result[3][1][4]=mdae

G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

C-index:  0.906724972403838
Mean squared error:  0.0016273930202831137
R-squared:  0.921823559394286
c_index: 0.906724972403838
Mean absolute error:  0.026784281641771848
Median absolute error:  0.01998076710895886

In [228]:
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, Y_train)
y_pred = rf.predict(X_test)

mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[4][1][0]=c_index
result[4][1][1]=mse
result[4][1][2]=r2
result[4][1][3]=mae
result[4][1][4]=mdae

C-index:  0.9963488154878153
Mean squared error:  0.0011448526213058315
R-squared:  0.9450037564151276
c_index: 0.9963488154878153
Mean absolute error:  0.006989113192966282
Median absolute error:  0.001063870171775623

In [229]:
z=[]
x=[]

for i in range(0,527):
    for j in range(0,519):
        if(nre1['Hugo'][i]==nre3['Hugo'][j]):
            z.append(nre1['Hugo'][i])
for i in range(0,len(z)):
    for j in range(0,520):
        if(z[i]==nre4['Hugo'][j]):
            x.append(z[i])

dfmerge = pd.DataFrame()
dfmerge['Hugo']=x

mdf=pd.merge(dfmerge,nre1,on='Hugo')
mdf=pd.merge(mdf,nre3,on='Hugo')
mdf=pd.merge(mdf,ne4,on='Hugo')

mdf = pd.DataFrame(mdf)
cl=pd.read_csv('CLINICALpreprocessed.CSV')
intersect= set.intersection(set(cl.index),set(mdf.index))
set(mdf.index)-intersect
for i in (set(mdf.index)-intersect):
    mdf.drop(i,inplace=True)
for i in (set(cl.index)-intersect):
    cl.drop(i,inplace=True)

cl.drop("Patient Identifier", axis=1,inplace=True)


print(cl.shape)
print(mdf.shape)
mdf=pd.concat([mdf,cl],axis=1)
mdf.drop("Hugo", axis=1,inplace=True)
mdf.columns = mdf.columns.astype(str)
scaler=per.MinMaxScaler(feature_range=(0,1))
rescaleData=scaler.fit_transform(mdf)
mdf=pd.DataFrame(rescaleData,index=mdf.index,columns=mdf.columns)
mdf.head()
df_train = mdf
df_test = df_train.sample(frac=0.3)
X_test=df_test
df_train = df_train.drop(df_test.index)
df_val = df_train.sample(frac=0.2)
X_train=df_train = df_train.drop(df_val.index)
df_train
get_target = lambda df: (df['Overall Survival (Months)'].values)
Y_train = get_target(df_train)

Y_test = get_target(df_test)
get_target = lambda df: (df['Overall Survival Status'].values)
E_train = get_target(df_train)
E_test = get_target(df_test)

# Exclude non-numeric columns from X_train and X_test
X_train_numeric = X_train.select_dtypes(include=[np.number])
X_test_numeric = X_test.select_dtypes(include=[np.number])
n_features = X_train.shape[1]
n_patients_train = X_train.shape[0]


# Drop columns containing string values from X_train and X_test
columns_to_drop = X_train.columns[X_train.applymap(type).eq(str).any()]
if 'Hugo' in columns_to_drop:
    columns_to_drop = columns_to_drop.drop('Hugo')

X_train_numeric = X_train_numeric.drop(columns=columns_to_drop, errors='ignore')
X_test_numeric = X_test_numeric.drop(columns=columns_to_drop, errors='ignore')

# Sorting
sort_idx = np.argsort(Y_train)[::-1]

# Use array indexing to select rows based on sort_idx
X_train_sorted = X_train_numeric.iloc[sort_idx, :]
Y_train_sorted = Y_train[sort_idx]


dsk = deepsurvk.DeepSurvK(n_features=n_features, E=E_train,)
callbacks = deepsurvk.common_callbacks()
print(callbacks)

epochs = 20
history = dsk.fit(X_train, Y_train, 
                  batch_size=n_patients_train,
                  epochs=epochs, 
                  callbacks=callbacks,
                  shuffle=False)
Y_pred_train = np.exp(-dsk.predict(X_train))
c_index_train = deepsurvk.concordance_index(Y_train, Y_pred_train, E_train)
print("DeepSurv")
print(f"c-index of training dataset = {c_index_train}")

Y_pred_test = np.exp(-dsk.predict(X_test))
c_index_test = deepsurvk.concordance_index(Y_test, Y_pred_test, E_test)
print(f"c-index of testing dataset = {c_index_test}")
Y_pred_trainn = (-dsk.predict(X_train))
Y_pred_testt = (-dsk.predict(X_test))

from sklearn.metrics import mean_squared_error
mse=mean_squared_error(Y_test,Y_pred_testt)

import math
rmse=math.sqrt(mse)

from sklearn.metrics import mean_absolute_error 
mae=mean_absolute_error (Y_test,Y_pred_testt)

from sklearn.metrics import median_absolute_error
mdae=median_absolute_error (Y_test,Y_pred_testt)

print("mse=",mse)
print("rmse=",rmse)
print("mae=",mae)
print("mdae=",mdae)
result[0][2][0]=c_index_test
result[0][2][1]=mse
result[0][2][2]=rmse
result[0][2][3]=mae
result[0][2][4]=mdae

(512, 26)
(512, 780)
[<keras.callbacks.EarlyStopping object at 0x00000187865C1A90>, <keras.callbacks.ModelCheckpoint object at 0x00000187865C1430>]
Epoch 1/20
1/1 [==============================] - 1s 815ms/step - loss: 176122.3906
Epoch 2/20
1/1 [==============================] - 0s 16ms/step - loss: 176411.4375
Epoch 3/20
1/1 [==============================] - 0s 16ms/step - loss: 176883.7500
Epoch 4/20
1/1 [==============================] - 0s 47ms/step - loss: 166956.1406
Epoch 5/20
1/1 [==============================] - 0s 48ms/step - loss: 157072.2031
Epoch 6/20
1/1 [==============================] - 0s 15ms/step - loss: 166328.7031
Epoch 7/20
1/1 [==============================] - 0s 16ms/step - loss: 159152.0625
Epoch 8/20
1/1 [==============================] - 0s 62ms/step - loss: 153061.9688
Epoch 9/20
1/1 [==============================] - 0s 16ms/step - loss: 159358.7344
Epoch 10/20
1/1 [==============================] - 0s 16ms/step - loss: 156143.7031
Epoch 11/20
1/1 [==============================] - 0s 16ms/step - loss: 153509.3281
Epoch 12/20
1/1 [==============================] - 0s 47ms/step - loss: 150214.3906
Epoch 13/20
1/1 [==============================] - 0s 47ms/step - loss: 149283.5781
Epoch 14/20
1/1 [==============================] - 0s 47ms/step - loss: 148486.7188
Epoch 15/20
1/1 [==============================] - 0s 67ms/step - loss: 145987.5312
Epoch 16/20
1/1 [==============================] - 0s 42ms/step - loss: 141692.5312
Epoch 17/20
1/1 [==============================] - 0s 47ms/step - loss: 139994.4844
Epoch 18/20
1/1 [==============================] - 0s 47ms/step - loss: 135940.9688
Epoch 19/20
1/1 [==============================] - 0s 47ms/step - loss: 135345.7344
Epoch 20/20
1/1 [==============================] - 0s 47ms/step - loss: 132265.7344
DeepSurv
c-index of training dataset = 0.78567254309925
c-index of testing dataset = 0.8129776712123483
mse= 53.724220224833175
rmse= 7.329680772368819
mae= 7.194153024651131
mdae= 7.373915969912531

In [230]:
param_grid = {
    "C": [0.1, 1, 10],
    "kernel": ["linear", "rbf", "poly"],
    "degree": [2, 3, 4],
    "epsilon": [0.01, 0.1, 1],
    "gamma": ["scale", "auto"]
}

svr = SVR()
grid_search = GridSearchCV(svr, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
print("SVR")
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
print("R-squared: ", r2)
result[1][2][0]=c_index
result[1][2][1]=mse
result[1][2][2]=r2
result[1][2][3]=mae
result[1][2][4]=mdae

SVR
C-index:  0.7688715292519317
Mean squared error:  0.010734824031551475
Mean absolute error:  0.0714871283747938
Median absolute error:  0.051068262623115125
R-squared:  0.542443587942838

In [231]:
param_grid = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.01, 0.1, 1],
    "max_depth": [1, 2, 3, 4]
}
xgb = XGBRegressor()
grid_search = GridSearchCV(xgb, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("XGBOOST")
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[2][2][0]=c_index
result[2][2][1]=mse
result[2][2][2]=r2
result[2][2][3]=mae
result[2][2][4]=mdae

XGBOOST
C-index:  0.9942260337946845
Mean squared error:  0.0005833067257386518
R-squared:  0.9751373910020941
c_index: 0.9942260337946845
Mean absolute error:  0.006010902267986244
Median absolute error:  0.0009807207505583282

In [232]:
param_grid = {
    "n_estimators": [50, 100],
    "learning_rate": [0.01, 0.1],
    "base_estimator__max_depth": [1, 2]
}
base_estimator = DecisionTreeRegressor()
adaboost = AdaBoostRegressor(base_estimator=base_estimator)
grid_search = GridSearchCV(adaboost, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[3][2][0]=c_index
result[3][2][1]=mse
result[3][2][2]=r2
result[3][2][3]=mae
result[3][2][4]=mdae

G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

C-index:  0.9085081090260677
Mean squared error:  0.0016586263356262057
R-squared:  0.9293034415056954
c_index: 0.9085081090260677
Mean absolute error:  0.031322944634530614
Median absolute error:  0.02603305068128831

In [233]:
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, Y_train)
y_pred = rf.predict(X_test)

mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[4][2][0]=c_index
result[4][2][1]=mse
result[4][2][2]=r2
result[4][2][3]=mae
result[4][2][4]=mdae

C-index:  0.9939712999915089
Mean squared error:  0.000750738569912926
R-squared:  0.9680008498106105
c_index: 0.9939712999915089
Mean absolute error:  0.008979338730928356
Median absolute error:  0.0011832115402866036

In [234]:
z=[]
x=[]

for i in range(0,527):
    for j in range(0,519):
        if(nrf1['Hugo'][i]==nrf3['Hugo'][j]):
            z.append(nrf1['Hugo'][i])
for i in range(0,len(z)):
    for j in range(0,520):
        if(z[i]==nrf4['Hugo'][j]):
            x.append(z[i])

dfmerge = pd.DataFrame()
dfmerge['Hugo']=x

mdf=pd.merge(dfmerge,nrf1,on='Hugo')
mdf=pd.merge(mdf,nrf3,on='Hugo')
mdf=pd.merge(mdf,nrf4,on='Hugo')

mdf = pd.DataFrame(mdf)
cl=pd.read_csv('CLINICALpreprocessed.CSV')
intersect= set.intersection(set(cl.index),set(mdf.index))
set(mdf.index)-intersect
for i in (set(mdf.index)-intersect):
    mdf.drop(i,inplace=True)
for i in (set(cl.index)-intersect):
    cl.drop(i,inplace=True)

cl.drop("Patient Identifier", axis=1,inplace=True)


print(cl.shape)
print(mdf.shape)
mdf=pd.concat([mdf,cl],axis=1)
mdf.drop("Hugo", axis=1,inplace=True)
mdf.columns = mdf.columns.astype(str)
scaler=per.MinMaxScaler(feature_range=(0,1))
rescaleData=scaler.fit_transform(mdf)
mdf=pd.DataFrame(rescaleData,index=mdf.index,columns=mdf.columns)
mdf.head()
df_train = mdf
df_test = df_train.sample(frac=0.3)
X_test=df_test
df_train = df_train.drop(df_test.index)
df_val = df_train.sample(frac=0.2)
X_train=df_train = df_train.drop(df_val.index)
df_train
get_target = lambda df: (df['Overall Survival (Months)'].values)
Y_train = get_target(df_train)

Y_test = get_target(df_test)
get_target = lambda df: (df['Overall Survival Status'].values)
E_train = get_target(df_train)
E_test = get_target(df_test)

# Exclude non-numeric columns from X_train and X_test
X_train_numeric = X_train.select_dtypes(include=[np.number])
X_test_numeric = X_test.select_dtypes(include=[np.number])
n_features = X_train.shape[1]
n_patients_train = X_train.shape[0]


# Drop columns containing string values from X_train and X_test
columns_to_drop = X_train.columns[X_train.applymap(type).eq(str).any()]
if 'Hugo' in columns_to_drop:
    columns_to_drop = columns_to_drop.drop('Hugo')

X_train_numeric = X_train_numeric.drop(columns=columns_to_drop, errors='ignore')
X_test_numeric = X_test_numeric.drop(columns=columns_to_drop, errors='ignore')

# Sorting
sort_idx = np.argsort(Y_train)[::-1]

# Use array indexing to select rows based on sort_idx
X_train_sorted = X_train_numeric.iloc[sort_idx, :]
Y_train_sorted = Y_train[sort_idx]


dsk = deepsurvk.DeepSurvK(n_features=n_features, E=E_train,)
callbacks = deepsurvk.common_callbacks()
print(callbacks)

epochs = 20
history = dsk.fit(X_train, Y_train, 
                  batch_size=n_patients_train,
                  epochs=epochs, 
                  callbacks=callbacks,
                  shuffle=False)
Y_pred_train = np.exp(-dsk.predict(X_train))
c_index_train = deepsurvk.concordance_index(Y_train, Y_pred_train, E_train)
print("DeepSurv")
print(f"c-index of training dataset = {c_index_train}")

Y_pred_test = np.exp(-dsk.predict(X_test))
c_index_test = deepsurvk.concordance_index(Y_test, Y_pred_test, E_test)
print(f"c-index of testing dataset = {c_index_test}")
Y_pred_trainn = (-dsk.predict(X_train))
Y_pred_testt = (-dsk.predict(X_test))

from sklearn.metrics import mean_squared_error
mse=mean_squared_error(Y_test,Y_pred_testt)

import math
rmse=math.sqrt(mse)

from sklearn.metrics import mean_absolute_error 
mae=mean_absolute_error (Y_test,Y_pred_testt)

from sklearn.metrics import median_absolute_error
mdae=median_absolute_error (Y_test,Y_pred_testt)

print("mse=",mse)
print("rmse=",rmse)
print("mae=",mae)
print("mdae=",mdae)
result[0][3][0]=c_index_test
result[0][3][1]=mse
result[0][3][2]=rmse
result[0][3][3]=mae
result[0][3][4]=mdae

(512, 26)
(512, 302)
[<keras.callbacks.EarlyStopping object at 0x00000187C4C7A160>, <keras.callbacks.ModelCheckpoint object at 0x00000187C4C7A100>]
Epoch 1/20
1/1 [==============================] - 1s 881ms/step - loss: 187217.5469
Epoch 2/20
1/1 [==============================] - 0s 7ms/step - loss: 190949.4219
Epoch 3/20
1/1 [==============================] - 0s 10ms/step - loss: 217261.9688
Epoch 4/20
1/1 [==============================] - 0s 7ms/step - loss: 197154.5156
Epoch 5/20
1/1 [==============================] - 0s 39ms/step - loss: 161094.2500
Epoch 6/20
1/1 [==============================] - 0s 18ms/step - loss: 168982.6406
Epoch 7/20
1/1 [==============================] - 0s 8ms/step - loss: 163661.4375
Epoch 8/20
1/1 [==============================] - 0s 10ms/step - loss: 163295.3438
Epoch 9/20
1/1 [==============================] - 0s 7ms/step - loss: 162862.7500
Epoch 10/20
1/1 [==============================] - 0s 57ms/step - loss: 154415.9844
Epoch 11/20
1/1 [==============================] - 0s 7ms/step - loss: 156499.6250
Epoch 12/20
1/1 [==============================] - 0s 7ms/step - loss: 165924.7969
Epoch 13/20
1/1 [==============================] - 0s 42ms/step - loss: 153290.8125
Epoch 14/20
1/1 [==============================] - 0s 22ms/step - loss: 162460.4844
Epoch 15/20
1/1 [==============================] - 0s 9ms/step - loss: 153713.2969
Epoch 16/20
1/1 [==============================] - 0s 48ms/step - loss: 152502.4688
Epoch 17/20
1/1 [==============================] - 0s 7ms/step - loss: 155757.9219
Epoch 18/20
1/1 [==============================] - 0s 40ms/step - loss: 147988.6250
Epoch 19/20
1/1 [==============================] - 0s 50ms/step - loss: 145393.4375
Epoch 20/20
1/1 [==============================] - 0s 19ms/step - loss: 149762.8594
DeepSurv
c-index of training dataset = 0.8204830917874396
c-index of testing dataset = 0.8128813559322033
mse= 24.168834253047255
rmse= 4.916180860489904
mae= 4.893884347302991
mdae= 4.706941423147331

In [235]:
param_grid = {
    "C": [0.1, 1, 10],
    "kernel": ["linear", "rbf", "poly"],
    "degree": [2, 3, 4],
    "epsilon": [0.01, 0.1, 1],
    "gamma": ["scale", "auto"]
}

svr = SVR()
grid_search = GridSearchCV(svr, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
print("SVR")
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
print("R-squared: ", r2)
result[1][3][0]=c_index
result[1][3][1]=mse
result[1][3][2]=r2
result[1][3][3]=mae
result[1][3][4]=mdae

SVR
C-index:  0.7946345190593429
Mean squared error:  0.0035639755314383764
Mean absolute error:  0.04790775558081341
Median absolute error:  0.040794264413816006
R-squared:  0.7039115257278237

In [236]:
param_grid = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.01, 0.1, 1],
    "max_depth": [1, 2, 3, 4]
}
xgb = XGBRegressor()
grid_search = GridSearchCV(xgb, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("XGBOOST")
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[2][3][0]=c_index
result[2][3][1]=mse
result[2][3][2]=r2
result[2][3][3]=mae
result[2][3][4]=mdae

XGBOOST
C-index:  0.988454028355548
Mean squared error:  1.7960251395847306e-05
R-squared:  0.9985078956388921
c_index: 0.988454028355548
Mean absolute error:  0.003008997402942448
Median absolute error:  0.0020134075800828585

In [237]:
param_grid = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.01, 0.1, 1],
    "base_estimator__max_depth": [1, 2, 3, 4]
}
base_estimator = DecisionTreeRegressor()
adaboost = AdaBoostRegressor(base_estimator=base_estimator)
grid_search = GridSearchCV(adaboost, param_grid, cv=5)
grid_search.fit(X_train, Y_train)
y_pred = grid_search.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[3][3][0]=c_index
result[3][3][1]=mse
result[3][3][2]=r2
result[3][3][3]=mae
result[3][3][4]=mdae

G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
G:\ana\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

C-index:  0.9973257492147042
Mean squared error:  0.00014835931817396865
R-squared:  0.9876745831236214
c_index: 0.9973257492147042
Mean absolute error:  0.0030945956836596032
Median absolute error:  0.0012882043773189307

In [238]:
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, Y_train)
y_pred = rf.predict(X_test)

mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)
c_index = concordance_index(Y_test, y_pred)
mae = mean_absolute_error(Y_test, y_pred)
medae = median_absolute_error(Y_test, y_pred)
print("C-index: ", c_index)
print("Mean squared error: ", mse)
print("R-squared: ", r2)
print("c_index:",c_index)
print("Mean absolute error: ", mae)
print("Median absolute error: ", medae)
result[4][3][0]=c_index
result[4][3][1]=mse
result[4][3][2]=r2
result[4][3][3]=mae
result[4][3][4]=mdae

C-index:  0.9963494354359453
Mean squared error:  7.041745180798438e-05
R-squared:  0.9941498487618556
c_index: 0.9963494354359453
Mean absolute error:  0.00257591985692964
Median absolute error:  0.0009779823479168937

In [239]:
!pip install pandas openpyxl
data_0_0 = result[0, 0:4, 0]
data_1_0 = result[3, 0:4, 0]
data_2_0 = result[2, 0:4, 0]
data_3_0 = result[1, 0:4, 0]
data_4_0 = result[4, 0:4, 0]
combined_data_0 = np.concatenate((data_0_0, data_1_0, data_2_0, data_3_0, data_4_0))
data_0_1 = result[0, 0:4, 1]
data_1_1 = result[3, 0:4, 1]
data_2_1 = result[2, 0:4, 1]
data_3_1 = result[1, 0:4, 1]
data_4_1 = result[4, 0:4, 1]
combined_data_1 = np.concatenate((data_0_1, data_1_1, data_2_1, data_3_1, data_4_1))
data_0_2 = result[0, 0:4, 2]
data_1_2 = result[3, 0:4, 2]
data_2_2 = result[2, 0:4, 2]
data_3_2 = result[1, 0:4, 2]
data_4_2 = result[4, 0:4, 2]
combined_data_2 = np.concatenate((data_0_2, data_1_2, data_2_2, data_3_2, data_4_2))
data_0_3 = result[0, 0:4, 3]
data_1_3 = result[3, 0:4, 3]
data_2_3 = result[2, 0:4, 3]
data_3_3 = result[1, 0:4, 3]
data_4_3 = result[4, 0:4, 3]
combined_data_3 = np.concatenate((data_0_3, data_1_3, data_2_3, data_3_3, data_4_3))
data_0_4 = result[0, 0:4, 4]
data_1_4 = result[3, 0:4, 4]
data_2_4 = result[2, 0:4, 4]
data_3_4 = result[1, 0:4, 4]
data_4_4 = result[4, 0:4, 4]
combined_data_4 = np.concatenate((data_0_4, data_1_4, data_2_4, data_3_4, data_4_4))
# Create a DataFrame
df = pd.DataFrame({
    'Combined_Data_0': combined_data_0,
    'Combined_Data_1': combined_data_1,
    'Combined_Data_2': combined_data_2,
    'Combined_Data_3': combined_data_3,
    'Combined_Data_4': combined_data_4
})

# Save the DataFrame to an Excel file
df.to_excel('combined_data.xlsx', index=False)

print("Data has been saved to combined_data.xlsx")

Requirement already satisfied: pandas in g:\ana\lib\site-packages (1.3.4)
Requirement already satisfied: openpyxl in g:\ana\lib\site-packages (3.0.9)
Requirement already satisfied: python-dateutil>=2.7.3 in g:\ana\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in g:\ana\lib\site-packages (from pandas) (1.20.0)
Requirement already satisfied: pytz>=2017.3 in g:\ana\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: et-xmlfile in g:\ana\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in g:\ana\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Data has been saved to combined_data.xlsx

WARNING: Ignoring invalid distribution -rotobuf (c:\users\pro deepali\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\pro deepali\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\pro deepali\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\pro deepali\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\pro deepali\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\pro deepali\appdata\roaming\python\python39\site-packages)